"""
Writes follow reads (decision 9).

Phase 0 closed PUT /me/list/{media_id}; the audit in the design doc found the
same hole on every other route taking a client-supplied entry id. These pin the
rule across all of them: if GET answers 404 for this viewer, the write answers
404 too, with the same message - a 403 would confirm the entry exists just as
surely as a 200 would.

The account under test holds manage.catalog and NOT label.nsfw. Before Phase A
that account could not exist, which is why this gap was unreachable until now.
"""

import uuid

from app import models
from app.services.rbac.permissions import PERM_MANAGE_CATALOG, label_perm, media_type_perm
from app.services.rbac.seed import default_user_permissions
from tests.api.conftest import HIDDEN_NAME, make_viewer


class TestFactoryWrites:
    """The nine per-type routers, generated by app/routers/_factory.py."""

    def test_update_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer()
        response = client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who Cannot See It"},
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_update_does_not_write(self, catalog_writer, hidden_anime, db_session):
        client = catalog_writer()
        client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who Cannot See It"},
        )
        db_session.refresh(hidden_anime)
        assert hidden_anime.anime_name_en == HIDDEN_NAME

    def test_patch_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer()
        response = client.patch(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed"},
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_complete_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        """The sharpest of the four: it writes a user_media_list row for the
        caller, which is the write Phase 0 closed on /api/me/list."""
        client = catalog_writer()
        response = client.post(f"/api/anime/{hidden_anime.system_id}/complete")
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_complete_leaves_no_list_row_behind(
        self, catalog_writer, hidden_anime, db_session
    ):
        """Counted, not asserted zero: the hidden_anime fixture already gives
        the entry a Completed row on the ACTING admin's list."""
        client = catalog_writer()
        rows = db_session.query(models.UserMediaList).filter(
            models.UserMediaList.media_id == hidden_anime.system_id
        )
        before = rows.count()
        client.post(f"/api/anime/{hidden_anime.system_id}/complete")
        assert rows.count() == before

    def test_delete_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime, db_session
    ):
        client = catalog_writer()
        response = client.delete(f"/api/anime/{hidden_anime.system_id}")
        assert response.status_code == 404
        assert (
            db_session.query(models.Anime)
            .filter(models.Anime.system_id == hidden_anime.system_id)
            .first()
            is not None
        )

    def test_the_gate_does_not_block_a_visible_entry(
        self, catalog_writer, sample_anime
    ):
        """The control: an unlabelled entry still writes, so this is a gate
        and not a blanket refusal."""
        client = catalog_writer()
        response = client.put(
            f"/api/anime/{sample_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who May"},
        )
        assert response.status_code == 200

    def test_holding_the_label_restores_the_write(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer(username="trustedcat", extra={label_perm("nsfw")})
        response = client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who May"},
        )
        assert response.status_code == 200

    def test_admin_is_unaffected(self, admin_client, hidden_anime):
        """is_superuser short-circuits entry_visible, so the owner's account
        sees no change on the day this lands."""
        response = admin_client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": HIDDEN_NAME},
        )
        assert response.status_code == 200


class TestCastingAndCredits:
    def test_replacing_a_cast_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer()
        response = client.put(
            f"/api/casting/anime/{hidden_anime.system_id}",
            json={"cast": []},
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_replacing_credits_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer()
        response = client.put(
            f"/api/credits/anime/{hidden_anime.system_id}",
            json={"credits": {}, "tags": {}},
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_credits_still_write_on_a_visible_entry(
        self, catalog_writer, sample_anime
    ):
        client = catalog_writer()
        response = client.put(
            f"/api/credits/anime/{sample_anime.system_id}",
            json={"credits": {}, "tags": {}},
        )
        assert response.status_code == 200


class TestQuoteAndMeme:
    def test_creating_a_quote_on_a_hidden_entry_is_refused(
        self, catalog_writer, hidden_anime, db_session
    ):
        client = catalog_writer()
        before = db_session.query(models.Quote).count()
        response = client.post(
            "/api/quote/",
            json={
                "media_type": "anime",
                "entry_id": str(hidden_anime.system_id),
                "text": "A line from a show I cannot see.",
            },
        )
        assert response.status_code == 404
        assert db_session.query(models.Quote).count() == before

    def test_patching_a_quote_onto_a_hidden_entry_is_refused(
        self, catalog_writer, hidden_anime, sample_anime, db_session, admin_user
    ):
        """The move case: the check runs against the INCOMING entry, not the
        stored one."""
        quote = models.Quote(
            system_id=uuid.uuid4(),
            media_type="anime",
            entry_id=sample_anime.system_id,
            text="A line from a show I can see.",
            author_id=admin_user.id,
        )
        db_session.add(quote)
        db_session.flush()
        client = catalog_writer()
        response = client.patch(
            f"/api/quote/{quote.system_id}",
            json={"entry_id": str(hidden_anime.system_id)},
        )
        assert response.status_code == 404
        db_session.refresh(quote)
        assert quote.entry_id == sample_anime.system_id

    def test_patching_only_entry_id_gates_on_the_new_entrys_own_type(
        self, db_session, client, sample_anime, sample_manga, admin_user
    ):
        """`Quote.media_type` is derived from `entry_id`, so a payload naming
        only `entry_id` must be gated on the INCOMING entry's own type - not
        the stored row's media_type, and not any media_type the payload
        happens to carry. A writer holding every media_type.* permission
        EXCEPT manga must be refused when moving a quote, by entry_id alone,
        from a visible anime onto a manga entry."""
        writer = make_viewer(
            db_session,
            client,
            "animeonlywriter",
            (default_user_permissions() - {media_type_perm("manga")})
            | {PERM_MANAGE_CATALOG},
        )
        quote = models.Quote(
            system_id=uuid.uuid4(),
            entry_id=sample_anime.system_id,
            text="A line from a show I can see.",
            author_id=admin_user.id,
        )
        db_session.add(quote)
        db_session.flush()
        response = writer.patch(
            f"/api/quote/{quote.system_id}",
            json={"entry_id": str(sample_manga.system_id)},
        )
        assert response.status_code == 404
        db_session.refresh(quote)
        assert quote.entry_id == sample_anime.system_id

    def test_creating_a_meme_on_a_hidden_entry_is_refused(
        self, catalog_writer, hidden_anime, db_session
    ):
        client = catalog_writer()
        before = db_session.query(models.Meme).count()
        response = client.post(
            "/api/meme/",
            json={
                "owner_type": "anime",
                "owner_id": str(hidden_anime.system_id),
                "text": "A meme about a show I cannot see",
            },
        )
        assert response.status_code == 404
        assert db_session.query(models.Meme).count() == before

    def test_a_meme_on_a_grouping_tier_still_writes(
        self, catalog_writer, sample_franchise
    ):
        """A tier carries no labels, so entry_visible has no opinion and the
        write must not be refused by accident."""
        client = catalog_writer()
        response = client.post(
            "/api/meme/",
            json={
                "owner_type": "franchise",
                "owner_id": str(sample_franchise.system_id),
                "text": "A meme about a franchise",
            },
        )
        assert response.status_code in (200, 201)


# A SCOPE_PERSONAL, SHAPE_TEXT, ALL_OWNERS section that is not a singleton -
# checked in app/utils/note_sections.py:204. "remark" is also personal but is
# singleton=True, which would add a second failure mode to every test here.
PERSONAL_SECTION = "advantages"


class TestNoteWrites:
    """note.py's POST is reachable with self.personal_notes and no catalogue
    permission at all - the same shape as the defect Phase 0 closed."""

    def _note_writer(self, db_session, client, username="notewriter"):
        return make_viewer(
            db_session, client, username, default_user_permissions()
        )

    def test_writing_a_personal_note_on_a_hidden_entry_is_refused(
        self, db_session, client, hidden_anime
    ):
        writer = self._note_writer(db_session, client)
        before = db_session.query(models.Note).count()
        response = writer.post(
            "/api/notes",
            json={
                "owner_type": "anime",
                "owner_id": str(hidden_anime.system_id),
                "section": PERSONAL_SECTION,
                "content": "A thought about a show I cannot see.",
            },
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text
        assert db_session.query(models.Note).count() == before

    def test_the_refusal_is_404_and_never_403(
        self, db_session, client, hidden_anime
    ):
        """403 is note.py's OWNERSHIP answer and must not be reused here: it
        would confirm the entry exists."""
        writer = self._note_writer(db_session, client)
        response = writer.post(
            "/api/notes",
            json={
                "owner_type": "anime",
                "owner_id": str(hidden_anime.system_id),
                "section": PERSONAL_SECTION,
                "content": "A thought.",
            },
        )
        assert response.status_code != 403

    def test_a_note_on_a_visible_entry_still_writes(
        self, db_session, client, sample_anime
    ):
        writer = self._note_writer(db_session, client, username="goodnotewriter")
        response = writer.post(
            "/api/notes",
            json={
                "owner_type": "anime",
                "owner_id": str(sample_anime.system_id),
                "section": PERSONAL_SECTION,
                "content": "A thought about a show I can see.",
            },
        )
        assert response.status_code == 201

    def test_patching_a_note_onto_a_hidden_entry_is_refused(
        self, db_session, client, sample_anime, hidden_anime
    ):
        """PATCH may move a note to a new owner (note.py:410), so the check has
        to run against the INCOMING owner, not the stored one."""
        writer = self._note_writer(db_session, client, username="movingwriter")
        created = writer.post(
            "/api/notes",
            json={
                "owner_type": "anime",
                "owner_id": str(sample_anime.system_id),
                "section": PERSONAL_SECTION,
                "content": "A thought.",
            },
        ).json()
        response = writer.patch(
            f"/api/notes/{created['system_id']}",
            json={
                "owner_type": "anime",
                "owner_id": str(hidden_anime.system_id),
            },
        )
        assert response.status_code == 404

    def test_patching_owner_id_alone_gates_on_the_new_entrys_own_type(
        self, db_session, client, sample_anime, sample_manga
    ):
        """
        Regression for the fix-round-1 finding: Note.owner_type is a
        read-only property read through Note.media, so `merged` (built by
        filling each field independently from the payload or the stored row)
        would otherwise pair a NEW owner_id with the OLD, stale owner_type
        when a PATCH names only owner_id. The writer holds every media_type
        permission EXCEPT manga, so a wrong-type gate (checking "anime",
        the stored type) would wrongly allow this, while the fixed gate
        (checking "manga", the type the id actually resolves to) refuses it.
        """
        permissions = default_user_permissions() - {media_type_perm("manga")}
        writer = make_viewer(
            db_session, client, "singlefieldwriter", permissions
        )
        created = writer.post(
            "/api/notes",
            json={
                "owner_type": "anime",
                "owner_id": str(sample_anime.system_id),
                "section": PERSONAL_SECTION,
                "content": "A thought.",
            },
        ).json()
        response = writer.patch(
            f"/api/notes/{created['system_id']}",
            json={"owner_id": str(sample_manga.system_id)},
        )
        assert response.status_code == 404
        moved = db_session.query(models.Note).filter(
            models.Note.system_id == created["system_id"]
        ).first()
        assert moved.media_id == sample_anime.system_id

    def test_patching_owner_id_alone_onto_a_visible_entry_still_writes(
        self, db_session, client, sample_anime, sample_manga
    ):
        """Control for the test above: a single-field owner_id PATCH is not
        blanket-refused, only refused when the resolved type is hidden."""
        writer = self._note_writer(db_session, client, username="okwriter")
        created = writer.post(
            "/api/notes",
            json={
                "owner_type": "anime",
                "owner_id": str(sample_anime.system_id),
                "section": PERSONAL_SECTION,
                "content": "A thought.",
            },
        ).json()
        response = writer.patch(
            f"/api/notes/{created['system_id']}",
            json={"owner_id": str(sample_manga.system_id)},
        )
        assert response.status_code == 200


class TestRelationAndWatchOrderWrites:
    def test_relating_to_a_hidden_entry_answers_as_a_missing_one(
        self, catalog_writer, hidden_anime, sample_anime, db_session
    ):
        """400 and the same message a nonexistent entry gets. The status is
        deliberately NOT 404 here: the route already answers 400 for a
        reference it cannot resolve, and a hidden entry must be that answer."""
        client = catalog_writer()
        before = db_session.query(models.MediaRelation).count()
        response = client.post(
            "/api/media-relation/",
            json={
                "from_type": "anime",
                "from_id": str(sample_anime.system_id),
                "kind": "sequel",
                "to_type": "anime",
                "to_id": str(hidden_anime.system_id),
            },
        )
        assert response.status_code == 400
        assert response.json()["detail"] == "Referenced entry does not exist."
        assert HIDDEN_NAME not in response.text
        assert db_session.query(models.MediaRelation).count() == before

    def test_a_relation_between_visible_entries_still_writes(
        self, catalog_writer, sample_anime, anime_with_studio
    ):
        """`sequel` is one of ACCEPTED_INPUT_KINDS
        (`app/utils/relation_kinds.py:58`); `anime_with_studio` is a second
        unlabelled anime, so both endpoints are visible."""
        client = catalog_writer()
        response = client.post(
            "/api/media-relation/",
            json={
                "from_type": "anime",
                "from_id": str(sample_anime.system_id),
                "kind": "sequel",
                "to_type": "anime",
                "to_id": str(anime_with_studio.system_id),
            },
        )
        assert response.status_code == 201

    def test_adding_a_hidden_entry_to_a_watch_order_answers_as_missing(
        self, admin_client, catalog_writer, hidden_anime, sample_franchise
    ):
        """The order is created through the API as admin rather than by
        constructing the model, so this test does not encode
        watch_order_list's column shape."""
        order = admin_client.post(
            "/api/watch-order/lists",
            json={
                "franchise_id": str(sample_franchise.system_id),
                "list_name": "An order",
            },
        ).json()
        client = catalog_writer()
        response = client.post(
            f"/api/watch-order/lists/{order['system_id']}/items",
            json={
                "media_type": "anime",
                "entry_id": str(hidden_anime.system_id),
            },
        )
        assert response.status_code == 400
        assert response.json()["detail"] == "Referenced entry does not exist."
        assert HIDDEN_NAME not in response.text
