"""
`alembic upgrade head` on an empty database must produce the models' schema.

This is the one thing the rest of the suite structurally cannot check.
`tests/api/conftest.py` builds its schema with `Base.metadata.create_all` and
never runs Alembic, so for 145 revisions nothing noticed that the chain could
not build a database at all: its first revision was an autogenerated DIFF
against a database that already existed, it altered a `seasonal` table no
revision ever created, and on an empty database the transaction aborted and
rolled back to zero tables. Every installation had come from `create_all`
instead, and the migrations were never the thing being run.

So this test runs the real command against a scratch database and compares the
result to `create_all`'s, object by object and column by column. Two specific
failures it would have caught on the day the baseline was written, both silent:

  * `collection.cover_franchise_id` is a CIRCULAR foreign key declared
    `use_alter=True`. SQLAlchemy omits such a constraint from CREATE TABLE and
    leaves `metadata.create_all()` to schedule a separate ALTER, which
    `op.create_table` does not do - so autogenerate wrote a
    ForeignKeyConstraint that was a no-op and the FK simply did not exist.
  * nine `<media>_public_id_seq` sequences hang off no column (media_sync
    registers them per media type), so autogenerate never emitted them.

Alembic runs as a SUBPROCESS rather than through its Python API because
alembic/env.py imports `SQLALCHEMY_DATABASE_URL` from app.database at module
scope and ignores alembic.ini's url. Pointing it at another database means
setting POSTGRES_DB before that import, which an already-running test process
cannot do - and a subprocess is what a human runs anyway.
"""

import os
import subprocess
import sys
import uuid
from pathlib import Path

import pytest
import sqlalchemy as sa
from sqlalchemy import text

from app import models
from app.config import settings

ROOT = Path(__file__).resolve().parents[2]

# Every named object the two schemas must agree on. Indexes, constraints,
# sequences, triggers and functions - the families autogenerate is known to
# drop on the floor, plus the ordinary ones for completeness.
OBJECTS_SQL = text(
    """
    select 'seq:' || sequencename from pg_sequences where schemaname = 'public'
    union all
    select 'trg:' || tgname from pg_trigger where not tgisinternal
    union all
    select 'fn:' || p.proname from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace where n.nspname = 'public'
    union all
    select 'con:' || conname from pg_constraint where contype in ('f', 'u', 'c', 'p')
    union all
    select 'ix:' || indexname from pg_indexes where schemaname = 'public'
    """
)

COLUMNS_SQL = text(
    """
    select table_name || '.' || column_name || ':' || data_type || ':'
           || is_nullable || ':' || coalesce(column_default, '-')
    from information_schema.columns
    where table_schema = 'public' and table_name <> 'alembic_version'
    """
)

# Alembic's own bookkeeping, which create_all has no reason to know about.
ALEMBIC_OWN = {"con:alembic_version_pkc", "ix:alembic_version_pkc"}


def _server_url(database: str) -> str:
    """The configured server, pointed at one named database.

    `render_as_string(hide_password=False)` rather than `str()`: SQLAlchemy's
    URL.__str__ masks the password as `***`, so str() hands back a URL that
    connects to the right host as the right user and fails authentication.
    That failure arrives here as a skip, not a red test, which is the worst
    shape it could take - the guard would sit green and never run.
    """
    url = sa.engine.url.make_url(settings.sqlalchemy_database_url)
    return url.set(database=database).render_as_string(hide_password=False)


@pytest.fixture
def scratch_databases():
    """Two empty databases, dropped afterwards whatever happens.

    Named with a uuid so a concurrent run in another worktree cannot collide -
    the pytest lock covers the suite, not somebody's manual session.
    """
    suffix = uuid.uuid4().hex[:8]
    names = (f"anime_mig_{suffix}", f"anime_create_{suffix}")

    admin = sa.create_engine(_server_url("postgres"), isolation_level="AUTOCOMMIT")
    try:
        with admin.connect() as conn:
            for name in names:
                conn.execute(text(f'CREATE DATABASE "{name}"'))
    except sa.exc.SQLAlchemyError as exc:  # pragma: no cover - environment
        admin.dispose()
        pytest.skip(f"cannot create a scratch database here: {exc}")

    try:
        yield names
    finally:
        with admin.connect() as conn:
            for name in names:
                conn.execute(
                    text(
                        "select pg_terminate_backend(pid) from pg_stat_activity "
                        "where datname = :n and pid <> pg_backend_pid()"
                    ),
                    {"n": name},
                )
                conn.execute(text(f'DROP DATABASE IF EXISTS "{name}"'))
        admin.dispose()


def _read(url: str, statement) -> set[str]:
    engine = sa.create_engine(url)
    try:
        with engine.connect() as conn:
            return {row[0] for row in conn.execute(statement)}
    finally:
        engine.dispose()


def test_upgrade_head_on_an_empty_database_matches_the_models(scratch_databases):
    migrated_db, created_db = scratch_databases

    result = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=ROOT,
        env={**os.environ, "POSTGRES_DB": migrated_db},
        capture_output=True,
        text=True,
    )
    # The original defect surfaced as a non-zero exit with the schema rolled
    # back, so the exit code alone is a real assertion - but the tables check
    # below is what makes an empty success impossible to mistake for a pass.
    assert result.returncode == 0, (
        f"alembic upgrade head failed on an empty database:\n"
        f"{result.stdout[-3000:]}\n{result.stderr[-3000:]}"
    )

    migrated_url = _server_url(migrated_db)
    created_url = _server_url(created_db)

    created_engine = sa.create_engine(created_url)
    try:
        models.Base.metadata.create_all(bind=created_engine)
    finally:
        created_engine.dispose()

    migrated_objects = _read(migrated_url, OBJECTS_SQL) - ALEMBIC_OWN
    created_objects = _read(created_url, OBJECTS_SQL)

    # Non-emptiness first. Both sides of a set comparison are satisfied by two
    # empty sets, and an empty set is exactly what the rolled-back run left
    # behind - so without this the headline assertion passes on the very
    # failure it exists to catch.
    assert len(created_objects) > 100, "create_all built nothing; the check is vacuous"

    missing = created_objects - migrated_objects
    assert not missing, (
        "the migrations do not build these, but the models declare them: "
        f"{sorted(missing)}"
    )

    extra = migrated_objects - created_objects
    assert not extra, (
        f"the migrations build objects the models do not declare: {sorted(extra)}"
    )


def test_the_migrated_columns_match_the_models(scratch_databases):
    """Types, nullability and defaults, not just the object names.

    A table can exist under both paths and still differ in a column default or
    a nullable flag, which the object-name comparison above would pass.
    """
    migrated_db, created_db = scratch_databases

    result = subprocess.run(
        [sys.executable, "-m", "alembic", "upgrade", "head"],
        cwd=ROOT,
        env={**os.environ, "POSTGRES_DB": migrated_db},
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr[-2000:]

    created_engine = sa.create_engine(_server_url(created_db))
    try:
        models.Base.metadata.create_all(bind=created_engine)
    finally:
        created_engine.dispose()

    migrated = _read(_server_url(migrated_db), COLUMNS_SQL)
    created = _read(_server_url(created_db), COLUMNS_SQL)

    assert len(created) > 300, "create_all built no columns; the check is vacuous"
    assert created - migrated == set(), sorted(created - migrated)[:20]
    assert migrated - created == set(), sorted(migrated - created)[:20]
