"""
Writes follow reads (decision 9).

Phase 0 closed PUT /me/list/{media_id}; the audit in the design doc found the
same hole on every other route taking a client-supplied entry id. These pin the
rule across all of them: if GET answers 404 for this viewer, the write answers
404 too, with the same message - a 403 would confirm the entry exists just as
surely as a 200 would.

The account under test holds manage.catalog and NOT label.nsfw. Before Phase A
that account could not exist, which is why this gap was unreachable until now.
"""

from app import models
from app.services.rbac.permissions import label_perm
from tests.api.conftest import HIDDEN_NAME


class TestFactoryWrites:
    """The nine per-type routers, generated by app/routers/_factory.py."""

    def test_update_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer()
        response = client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who Cannot See It"},
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_update_does_not_write(self, catalog_writer, hidden_anime, db_session):
        client = catalog_writer()
        client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who Cannot See It"},
        )
        db_session.refresh(hidden_anime)
        assert hidden_anime.anime_name_en == HIDDEN_NAME

    def test_patch_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer()
        response = client.patch(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed"},
        )
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_complete_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime
    ):
        """The sharpest of the four: it writes a user_media_list row for the
        caller, which is the write Phase 0 closed on /api/me/list."""
        client = catalog_writer()
        response = client.post(f"/api/anime/{hidden_anime.system_id}/complete")
        assert response.status_code == 404
        assert HIDDEN_NAME not in response.text

    def test_complete_leaves_no_list_row_behind(
        self, catalog_writer, hidden_anime, db_session
    ):
        """Counted, not asserted zero: the hidden_anime fixture already gives
        the entry a Completed row on the ACTING admin's list."""
        client = catalog_writer()
        rows = db_session.query(models.UserMediaList).filter(
            models.UserMediaList.media_id == hidden_anime.system_id
        )
        before = rows.count()
        client.post(f"/api/anime/{hidden_anime.system_id}/complete")
        assert rows.count() == before

    def test_delete_is_indistinguishable_from_missing(
        self, catalog_writer, hidden_anime, db_session
    ):
        client = catalog_writer()
        response = client.delete(f"/api/anime/{hidden_anime.system_id}")
        assert response.status_code == 404
        assert (
            db_session.query(models.Anime)
            .filter(models.Anime.system_id == hidden_anime.system_id)
            .first()
            is not None
        )

    def test_the_gate_does_not_block_a_visible_entry(
        self, catalog_writer, sample_anime
    ):
        """The control: an unlabelled entry still writes, so this is a gate
        and not a blanket refusal."""
        client = catalog_writer()
        response = client.put(
            f"/api/anime/{sample_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who May"},
        )
        assert response.status_code == 200

    def test_holding_the_label_restores_the_write(
        self, catalog_writer, hidden_anime
    ):
        client = catalog_writer(username="trustedcat", extra={label_perm("nsfw")})
        response = client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": "Renamed By Someone Who May"},
        )
        assert response.status_code == 200

    def test_admin_is_unaffected(self, admin_client, hidden_anime):
        """is_superuser short-circuits entry_visible, so the owner's account
        sees no change on the day this lands."""
        response = admin_client.put(
            f"/api/anime/{hidden_anime.system_id}",
            json={"anime_name_en": HIDDEN_NAME},
        )
        assert response.status_code == 200
