"""v2_schema_alignment

Revision ID: 020f72b0a309
Revises: 708e4a1a76c5
Create Date: 2026-03-14 19:39:12.620966

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "020f72b0a309"
down_revision: Union[str, Sequence[str], None] = "708e4a1a76c5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Type Conversions with explicit casting
    op.alter_column(
        "anime_entries",
        "watch_order_rec",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="watch_order_rec::double precision",
    )

    op.alter_column(
        "anime_entries",
        "seiyuu",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
    )

    op.alter_column(
        "anime_entries",
        "source_baha",
        existing_type=sa.VARCHAR(),
        type_=sa.Boolean(),
        existing_nullable=True,
        postgresql_using="source_baha::boolean",
    )

    # 2. Data Cleanup: Remove duplicate series_en entries before creating unique index
    # This keeps the record with the lexicographically smallest system_id for each series_en
    op.execute(
        """
        DELETE FROM anime_series
        WHERE system_id NOT IN (
            SELECT MIN(system_id)
            FROM anime_series
            GROUP BY series_en
        )
    """
    )

    # 3. Index adjustments
    op.drop_index(op.f("ix_anime_series_series_en"), table_name="anime_series")
    op.create_index(
        op.f("ix_anime_series_series_en"), "anime_series", ["series_en"], unique=True
    )

    # 4. Update System Options nullability
    op.alter_column(
        "system_options", "category", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column(
        "system_options", "option_value", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "system_options", "option_value", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "system_options", "category", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_index(op.f("ix_anime_series_series_en"), table_name="anime_series")
    op.create_index(
        op.f("ix_anime_series_series_en"), "anime_series", ["series_en"], unique=False
    )

    op.alter_column(
        "anime_entries",
        "source_baha",
        existing_type=sa.Boolean(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "anime_entries",
        "seiyuu",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "anime_entries",
        "watch_order_rec",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
