"""v2_schema

Revision ID: 2b0220b5a174
Revises: e4f831d8b802
Create Date: 2026-03-11 00:25:48.579979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b0220b5a174'
down_revision: Union[str, Sequence[str], None] = 'e4f831d8b802'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_options',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('option_value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_options_category'), 'system_options', ['category'], unique=False)
    op.create_index(op.f('ix_system_options_id'), 'system_options', ['id'], unique=False)
    op.add_column('anime_entries', sa.Column('anime_alt_name', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('release_month', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('release_season', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('release_year', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('music', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('prequel', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('sequel', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('alternative', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('watch_order', sa.Float(), nullable=True))
    op.add_column('anime_entries', sa.Column('watch_order_rec', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('baha_link', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('source_other', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('source_other_link', sa.String(), nullable=True))
    op.add_column('anime_entries', sa.Column('cover_image_file', sa.String(), nullable=True))
    op.alter_column('anime_entries', 'mal_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('anime_entries', 'mal_rating',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_anime_entries_series_en'), 'anime_entries', ['series_en'], unique=False)
    op.drop_column('anime_entries', 'release_date')
    op.drop_column('anime_entries', 'cover_image_url')
    op.add_column('anime_series', sa.Column('series_alt_name', sa.String(), nullable=True))
    op.add_column('anime_series', sa.Column('series_expectation', sa.String(), nullable=True))
    op.add_column('anime_series', sa.Column('favorite_3x3_slot', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_anime_series_series_en'), 'anime_series', ['series_en'], unique=False)
    op.drop_column('anime_series', 'alt_name')
    op.add_column('deleted_records', sa.Column('table_name', sa.String(), nullable=True))
    op.add_column('deleted_records', sa.Column('data_json', sa.Text(), nullable=True))
    op.drop_column('deleted_records', 'title')
    op.drop_column('deleted_records', 'record_type')
    op.alter_column('sync_logs', 'error_message',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sync_logs', 'error_message',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('deleted_records', sa.Column('record_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deleted_records', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('deleted_records', 'data_json')
    op.drop_column('deleted_records', 'table_name')
    op.add_column('anime_series', sa.Column('alt_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_anime_series_series_en'), table_name='anime_series')
    op.drop_column('anime_series', 'favorite_3x3_slot')
    op.drop_column('anime_series', 'series_expectation')
    op.drop_column('anime_series', 'series_alt_name')
    op.add_column('anime_entries', sa.Column('cover_image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('anime_entries', sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_anime_entries_series_en'), table_name='anime_entries')
    op.alter_column('anime_entries', 'mal_rating',
               existing_type=sa.String(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('anime_entries', 'mal_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('anime_entries', 'cover_image_file')
    op.drop_column('anime_entries', 'source_other_link')
    op.drop_column('anime_entries', 'source_other')
    op.drop_column('anime_entries', 'baha_link')
    op.drop_column('anime_entries', 'watch_order_rec')
    op.drop_column('anime_entries', 'watch_order')
    op.drop_column('anime_entries', 'alternative')
    op.drop_column('anime_entries', 'sequel')
    op.drop_column('anime_entries', 'prequel')
    op.drop_column('anime_entries', 'music')
    op.drop_column('anime_entries', 'release_year')
    op.drop_column('anime_entries', 'release_season')
    op.drop_column('anime_entries', 'release_month')
    op.drop_column('anime_entries', 'anime_alt_name')
    op.drop_index(op.f('ix_system_options_id'), table_name='system_options')
    op.drop_index(op.f('ix_system_options_category'), table_name='system_options')
    op.drop_table('system_options')
    # ### end Alembic commands ###
