"""baseline schema

Revision ID: 4832c83905a3
Revises:
Create Date: 2026-09-12

The whole schema in one revision, replacing 145 that could not build it.

The old chain had no foundation. Alembic was adopted against a database that
already existed, so revision 1 (`86982d71c2f1`) was an autogenerated DIFF - its
first statement altered a `seasonal` table that no revision ever created. On an
empty database that aborted the transaction, `except Exception` swallowed it,
and every later statement failed with InFailedSqlTransaction while the same
handlers printed "already exists, skipping" on an empty database. The run
rolled back to zero tables. Nothing caught it because tests/api/conftest.py
builds its schema with `Base.metadata.create_all` and never runs Alembic.

The 145 revisions are in alembic/versions_archive/, out of the chain and still
readable; git has them either way. Nothing needs to replay them - every
database that exists is at or past the old head and is stamped here instead.

TWO THINGS AUTOGENERATE DID NOT EMIT, both added by hand below and both
verified by diffing this migration's schema against `create_all`'s with
pg_dump:

  sequences  `Column(Integer, Sequence("x_seq"))` makes create_all issue a
             separate CREATE SEQUENCE. Alembic's op.create_table drops the
             Sequence from the column entirely, so the sequences are created
             explicitly here.

  triggers   `delete_media_row()` and one AFTER DELETE trigger per detail
             table stop a detail delete orphaning its `media` row. They are
             attached in app/models/media_sync.py as `after_create` DDL
             listeners on the Table objects, and op.create_table builds its
             OWN Table, so those listeners never fire during a migration.

Both are frozen as literal SQL rather than imported from app.models. A
migration is a snapshot: if it imported the models it would describe whatever
they say the day it runs, not the day it was written, and the next revision
would be diffing against a moving target.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4832c83905a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# --- DDL autogenerate does not emit -----------------------------------------
# Frozen literals, deliberately. See the module docstring.

SEQUENCES = (
    # Declared on a column as Column(Integer, Sequence("x_seq")).
    "character_public_id_seq",
    "collection_public_id_seq",
    "franchise_public_id_seq",
    "person_public_id_seq",
    "publisher_public_id_seq",
    "series_public_id_seq",
    "studio_public_id_seq",
    "watch_order_list_public_id_seq",
    # Registered per media type in media_sync.register_media_sync, so they
    # hang off no column at all and autogenerate never saw them.
    "anime_public_id_seq",
    "anime_movies_public_id_seq",
    "cartoons_public_id_seq",
    "comic_public_id_seq",
    "games_public_id_seq",
    "manga_public_id_seq",
    "movies_public_id_seq",
    "novel_public_id_seq",
    "tv_shows_public_id_seq",
)

# One AFTER DELETE trigger per detail table, all calling the same function.
MEDIA_TABLES = (
    "anime",
    "anime_movies",
    "cartoons",
    "comic",
    "games",
    "manga",
    "movies",
    "novel",
    "tv_shows",
)

DELETE_MEDIA_FUNCTION = """
CREATE OR REPLACE FUNCTION delete_media_row() RETURNS trigger AS $$
BEGIN
    DELETE FROM media WHERE system_id = OLD.system_id;
    RETURN OLD;
END;
$$ LANGUAGE plpgsql
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_mode',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_access_mode_key'), 'access_mode', ['key'], unique=True)
    op.create_index(op.f('ix_access_mode_system_id'), 'access_mode', ['system_id'], unique=False)
    op.create_table('character',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_cn', sa.String(), nullable=True),
    sa.Column('name_jp', sa.String(), nullable=True),
    sa.Column('name_alt', sa.String(), nullable=True),
    sa.Column('display_name_field', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('photo_file', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(name_en, name_cn, name_jp, name_alt) >= 1', name='ck_character_has_a_name'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_character_public_id')
    )
    op.create_index(op.f('ix_character_name_en'), 'character', ['name_en'], unique=False)
    op.create_index(op.f('ix_character_system_id'), 'character', ['system_id'], unique=False)
    op.create_table('collection',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('collection_name_en', sa.String(), nullable=True),
    sa.Column('collection_name_cn', sa.String(), nullable=True),
    sa.Column('collection_name_roman', sa.String(), nullable=True),
    sa.Column('collection_name_jp', sa.String(), nullable=True),
    sa.Column('collection_name_alt', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('collection_expectation', sa.String(), nullable=True),
    sa.Column('cover_franchise_id', sa.UUID(), nullable=True),
    sa.Column('no_built_in_orders', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cover_franchise_id'], ['franchise.system_id'], name='fk_collection_cover_franchise_id', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_collection_public_id')
    )
    op.create_index(op.f('ix_collection_system_id'), 'collection', ['system_id'], unique=False)
    op.create_table('content_label',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_content_label_key'), 'content_label', ['key'], unique=True)
    op.create_index(op.f('ix_content_label_system_id'), 'content_label', ['system_id'], unique=False)
    op.create_table('data_control_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_main', sa.String(), nullable=False),
    sa.Column('action_specific', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rows_added', sa.Integer(), nullable=True),
    sa.Column('rows_updated', sa.Integer(), nullable=True),
    sa.Column('rows_deleted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_control_logs_id'), 'data_control_logs', ['id'], unique=False)
    op.create_table('deleted_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('franchise_type', sa.String(), nullable=True),
    sa.Column('franchise_cn', sa.String(), nullable=True),
    sa.Column('series_cn', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('name_cn', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_record_id'), 'deleted_record', ['id'], unique=False)
    op.create_table('media_relation',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('from_type', sa.String(), nullable=False),
    sa.Column('from_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('to_type', sa.String(), nullable=False),
    sa.Column('to_id', sa.UUID(), nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('NOT (from_type = to_type AND from_id = to_id)', name='ck_media_relation_no_self'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('from_type', 'from_id', 'relation_type', 'to_type', 'to_id', name='uq_media_relation_pair')
    )
    op.create_index('ix_media_relation_from', 'media_relation', ['from_type', 'from_id'], unique=False)
    op.create_index(op.f('ix_media_relation_system_id'), 'media_relation', ['system_id'], unique=False)
    op.create_index('ix_media_relation_to', 'media_relation', ['to_type', 'to_id'], unique=False)
    op.create_table('person',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_cn', sa.String(), nullable=True),
    sa.Column('name_jp', sa.String(), nullable=True),
    sa.Column('name_alt', sa.String(), nullable=True),
    sa.Column('display_name_field', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('photo_file', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(name_en, name_cn, name_jp, name_alt) >= 1', name='ck_person_has_a_name'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('name_en', 'name_cn', 'name_jp', 'name_alt', name='uq_person_name', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_person_public_id')
    )
    op.create_index(op.f('ix_person_name_en'), 'person', ['name_en'], unique=False)
    op.create_index(op.f('ix_person_system_id'), 'person', ['system_id'], unique=False)
    op.create_table('publisher',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_cn', sa.String(), nullable=True),
    sa.Column('name_jp', sa.String(), nullable=True),
    sa.Column('name_alt', sa.String(), nullable=True),
    sa.Column('display_name_field', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('logo_file', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.String(), nullable=True),
    sa.Column('defunct_date', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("defunct_date IS NULL OR defunct_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_publisher_defunct_date'),
    sa.CheckConstraint("founded_date IS NULL OR founded_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_publisher_founded_date'),
    sa.CheckConstraint('num_nonnulls(name_en, name_cn, name_jp, name_alt) >= 1', name='ck_publisher_has_a_name'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('name_en', 'name_cn', 'name_jp', 'name_alt', name='uq_publisher_name', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_publisher_public_id')
    )
    op.create_index(op.f('ix_publisher_name_en'), 'publisher', ['name_en'], unique=False)
    op.create_index(op.f('ix_publisher_system_id'), 'publisher', ['system_id'], unique=False)
    op.create_table('role',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_index(op.f('ix_role_system_id'), 'role', ['system_id'], unique=False)
    op.create_table('studio',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('name_cn', sa.String(), nullable=True),
    sa.Column('name_jp', sa.String(), nullable=True),
    sa.Column('name_alt', sa.String(), nullable=True),
    sa.Column('display_name_field', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('logo_file', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('founded_date', sa.String(), nullable=True),
    sa.Column('defunct_date', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('mal_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("defunct_date IS NULL OR defunct_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_studio_defunct_date'),
    sa.CheckConstraint("founded_date IS NULL OR founded_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_studio_founded_date'),
    sa.CheckConstraint('num_nonnulls(name_en, name_cn, name_jp, name_alt) >= 1', name='ck_studio_has_a_name'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('name_en', 'name_cn', 'name_jp', 'name_alt', name='uq_studio_name', postgresql_nulls_not_distinct=True),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_studio_public_id')
    )
    op.create_index(op.f('ix_studio_name_en'), 'studio', ['name_en'], unique=False)
    op.create_index(op.f('ix_studio_system_id'), 'studio', ['system_id'], unique=False)
    op.create_table('system_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_config_key'), 'system_configs', ['config_key'], unique=True)
    op.create_index(op.f('ix_system_configs_id'), 'system_configs', ['id'], unique=False)
    op.create_table('system_option',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('category', 'value', name='uq_system_option_value')
    )
    op.create_index(op.f('ix_system_option_category'), 'system_option', ['category'], unique=False)
    op.create_index(op.f('ix_system_option_system_id'), 'system_option', ['system_id'], unique=False)
    op.create_table('access_mode_field_group',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('field_group_key', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mode_id'], ['access_mode.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('mode_id', 'field_group_key', name='uq_access_mode_field_group')
    )
    op.create_index(op.f('ix_access_mode_field_group_mode_id'), 'access_mode_field_group', ['mode_id'], unique=False)
    op.create_index(op.f('ix_access_mode_field_group_system_id'), 'access_mode_field_group', ['system_id'], unique=False)
    op.create_table('access_mode_label',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['content_label.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mode_id'], ['access_mode.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('mode_id', 'label_id', name='uq_access_mode_label')
    )
    op.create_index(op.f('ix_access_mode_label_label_id'), 'access_mode_label', ['label_id'], unique=False)
    op.create_index(op.f('ix_access_mode_label_mode_id'), 'access_mode_label', ['mode_id'], unique=False)
    op.create_index(op.f('ix_access_mode_label_system_id'), 'access_mode_label', ['system_id'], unique=False)
    op.create_table('character_casting',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('entry_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('photo_file', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("person_id IS NULL OR media_type IN ('anime', 'anime-movie')", name='ck_casting_voice_scope'),
    sa.ForeignKeyConstraint(['character_id'], ['character.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('character_id', 'media_type', 'entry_id', name='uq_character_casting')
    )
    op.create_index(op.f('ix_character_casting_character_id'), 'character_casting', ['character_id'], unique=False)
    op.create_index('ix_character_casting_entry', 'character_casting', ['media_type', 'entry_id'], unique=False)
    op.create_index(op.f('ix_character_casting_person_id'), 'character_casting', ['person_id'], unique=False)
    op.create_index(op.f('ix_character_casting_system_id'), 'character_casting', ['system_id'], unique=False)
    op.create_table('franchise',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('franchise_type', sa.String(), nullable=True),
    sa.Column('franchise_name_en', sa.String(), nullable=True),
    sa.Column('franchise_name_cn', sa.String(), nullable=True),
    sa.Column('franchise_name_roman', sa.String(), nullable=True),
    sa.Column('franchise_name_jp', sa.String(), nullable=True),
    sa.Column('franchise_name_alt', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('franchise_expectation', sa.String(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('cover_entry_id', sa.UUID(), nullable=True),
    sa.Column('type_covers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('type_slots', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size_group_derived', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size_group_manual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_franchise_public_id')
    )
    op.create_index(op.f('ix_franchise_collection_id'), 'franchise', ['collection_id'], unique=False)
    op.create_index(op.f('ix_franchise_system_id'), 'franchise', ['system_id'], unique=False)
    op.create_table('person_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'role', 'scope', name='uq_person_role')
    )
    op.create_index(op.f('ix_person_role_person_id'), 'person_role', ['person_id'], unique=False)
    op.create_index(op.f('ix_person_role_role'), 'person_role', ['role'], unique=False)
    op.create_table('publisher_scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('publisher_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publisher_id', 'scope', name='uq_publisher_scope')
    )
    op.create_index(op.f('ix_publisher_scope_publisher_id'), 'publisher_scope', ['publisher_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permission_id'), 'role_permission', ['id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('system_option_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['system_option.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'source', 'value', name='uq_system_option_alias')
    )
    op.create_index('ix_system_option_alias_lookup', 'system_option_alias', ['source', 'value'], unique=False)
    op.create_index(op.f('ix_system_option_alias_option_id'), 'system_option_alias', ['option_id'], unique=False)
    op.create_table('system_option_scope',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['system_option.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'scope', name='uq_system_option_scope')
    )
    op.create_index(op.f('ix_system_option_scope_option_id'), 'system_option_scope', ['option_id'], unique=False)
    op.create_table('system_option_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('usage', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['system_option.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_id', 'usage', name='uq_system_option_usage')
    )
    op.create_index(op.f('ix_system_option_usage_option_id'), 'system_option_usage', ['option_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('list_is_public', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_installation_owner', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.system_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_one_installation_owner', 'users', [sa.literal_column('(true)')], unique=True, postgresql_where=sa.text('is_installation_owner'))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('seasonal',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seasonal', sa.String(), nullable=False),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('entry_planned', sa.Integer(), nullable=False),
    sa.Column('entry_completed', sa.Integer(), nullable=False),
    sa.Column('entry_watching', sa.Integer(), nullable=False),
    sa.Column('entry_dropped', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_seasonal_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'seasonal')
    )
    op.create_index(op.f('ix_seasonal_seasonal'), 'seasonal', ['seasonal'], unique=False)
    op.create_table('series',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('series_name_en', sa.String(), nullable=True),
    sa.Column('series_name_cn', sa.String(), nullable=True),
    sa.Column('series_name_roman', sa.String(), nullable=True),
    sa.Column('series_name_jp', sa.String(), nullable=True),
    sa.Column('series_name_alt', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('series_expectation', sa.String(), nullable=True),
    sa.Column('cover_entry_id', sa.UUID(), nullable=True),
    sa.Column('size_group_derived', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('size_group_manual', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_series_public_id')
    )
    op.create_index(op.f('ix_series_system_id'), 'series', ['system_id'], unique=False)
    op.create_table('user_access_mode',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mode_id', sa.UUID(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mode_id'], ['access_mode.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('user_id', 'mode_id', name='uq_user_access_mode')
    )
    op.create_index('ix_one_default_mode_per_user', 'user_access_mode', ['user_id'], unique=True, postgresql_where=sa.text('is_default'))
    op.create_index(op.f('ix_user_access_mode_mode_id'), 'user_access_mode', ['mode_id'], unique=False)
    op.create_index(op.f('ix_user_access_mode_system_id'), 'user_access_mode', ['system_id'], unique=False)
    op.create_index(op.f('ix_user_access_mode_user_id'), 'user_access_mode', ['user_id'], unique=False)
    op.create_table('media',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('cover_image_file', sa.String(), nullable=True),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('media_type', 'public_id', deferrable=True, initially='DEFERRED', name='uq_media_type_public_id'),
    sa.UniqueConstraint('system_id', 'media_type', name='uq_media_id_type')
    )
    op.create_index(op.f('ix_media_display_name'), 'media', ['display_name'], unique=False)
    op.create_index(op.f('ix_media_media_type'), 'media', ['media_type'], unique=False)
    op.create_index(op.f('ix_media_system_id'), 'media', ['system_id'], unique=False)
    op.create_table('user_access_mode_denial',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('user_access_mode_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=True),
    sa.Column('field_group_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(label_id IS NOT NULL)::int + (field_group_key IS NOT NULL)::int = 1', name='ck_denial_names_one_thing'),
    sa.ForeignKeyConstraint(['label_id'], ['content_label.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_access_mode_id'], ['user_access_mode.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('user_access_mode_id', 'field_group_key', name='uq_denial_field_group'),
    sa.UniqueConstraint('user_access_mode_id', 'label_id', name='uq_denial_label')
    )
    op.create_index(op.f('ix_user_access_mode_denial_system_id'), 'user_access_mode_denial', ['system_id'], unique=False)
    op.create_index(op.f('ix_user_access_mode_denial_user_access_mode_id'), 'user_access_mode_denial', ['user_access_mode_id'], unique=False)
    op.create_table('watch_order_list',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('public_id', sa.Integer(), nullable=False),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('list_name', sa.String(), nullable=True),
    sa.Column('list_type', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_most_recommended', sa.Boolean(), nullable=True),
    sa.Column('auto_source', sa.String(), nullable=True),
    sa.Column('sort_index', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(CASE WHEN franchise_id IS NULL THEN 0 ELSE 1 END + CASE WHEN collection_id IS NULL THEN 0 ELSE 1 END + CASE WHEN series_id IS NULL THEN 0 ELSE 1 END) = 1', name='ck_watch_order_list_single_owner'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('public_id', deferrable=True, initially='DEFERRED', name='uq_watch_order_list_public_id')
    )
    op.create_index(op.f('ix_watch_order_list_collection_id'), 'watch_order_list', ['collection_id'], unique=False)
    op.create_index(op.f('ix_watch_order_list_franchise_id'), 'watch_order_list', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_watch_order_list_series_id'), 'watch_order_list', ['series_id'], unique=False)
    op.create_index(op.f('ix_watch_order_list_system_id'), 'watch_order_list', ['system_id'], unique=False)
    op.create_table('anime',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='anime', nullable=False),
    sa.Column('anime_name_en', sa.String(), nullable=True),
    sa.Column('anime_name_cn', sa.String(), nullable=True),
    sa.Column('anime_name_roman', sa.String(), nullable=True),
    sa.Column('anime_name_jp', sa.String(), nullable=True),
    sa.Column('anime_name_alt', sa.String(), nullable=True),
    sa.Column('season_part', sa.String(), nullable=True),
    sa.Column('airing_type', sa.String(), nullable=True),
    sa.Column('airing_status', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('is_main_entry', sa.Boolean(), nullable=True),
    sa.Column('ep_previous', sa.Integer(), nullable=True),
    sa.Column('ep_total', sa.Integer(), nullable=True),
    sa.Column('ep_special', sa.Float(), nullable=True),
    sa.Column('mal_rating', sa.Float(), nullable=True),
    sa.Column('mal_rank', sa.String(), nullable=True),
    sa.Column('anilist_rating', sa.String(), nullable=True),
    sa.Column('release_season', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('broadcast_day', sa.String(), nullable=True),
    sa.Column('broadcast_time', sa.Time(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('mal_link', sa.String(), nullable=True),
    sa.Column('seiyuu', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("media_type = 'anime'", name='ck_anime_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_anime_release_date_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_anime_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_anime_system_id'), 'anime', ['system_id'], unique=False)
    op.create_table('anime_movies',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='anime-movie', nullable=False),
    sa.Column('anime_movie_name_en', sa.String(), nullable=True),
    sa.Column('anime_movie_name_cn', sa.String(), nullable=True),
    sa.Column('anime_movie_name_roman', sa.String(), nullable=True),
    sa.Column('anime_movie_name_jp', sa.String(), nullable=True),
    sa.Column('anime_movie_name_alt', sa.String(), nullable=True),
    sa.Column('airing_status', sa.String(), nullable=True),
    sa.Column('mal_rating', sa.Float(), nullable=True),
    sa.Column('mal_rank', sa.String(), nullable=True),
    sa.Column('anilist_rating', sa.String(), nullable=True),
    sa.Column('length_min', sa.Integer(), nullable=True),
    sa.Column('release_date_jp', sa.String(), nullable=True),
    sa.Column('release_date_tw', sa.String(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('mal_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("media_type = 'anime-movie'", name='ck_anime_movies_media_type'),
    sa.CheckConstraint("release_date_jp ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_anime_movies_release_date_jp_iso'),
    sa.CheckConstraint("release_date_tw ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_anime_movies_release_date_tw_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_anime_movies_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_anime_movies_system_id'), 'anime_movies', ['system_id'], unique=False)
    op.create_table('cartoons',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='cartoon', nullable=False),
    sa.Column('cartoon_name_en', sa.String(), nullable=True),
    sa.Column('cartoon_name_cn', sa.String(), nullable=True),
    sa.Column('cartoon_name_alt', sa.String(), nullable=True),
    sa.Column('season_part', sa.String(), nullable=True),
    sa.Column('airing_type', sa.String(), nullable=True),
    sa.Column('airing_status', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('ep_total', sa.Integer(), nullable=True),
    sa.Column('length_ep_min', sa.Integer(), nullable=True),
    sa.Column('imdb_rating', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('imdb_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("media_type = 'cartoon'", name='ck_cartoons_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_cartoons_release_date_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_cartoons_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_cartoons_system_id'), 'cartoons', ['system_id'], unique=False)
    op.create_table('comic',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='comic', nullable=False),
    sa.Column('comic_name_en', sa.String(), nullable=True),
    sa.Column('comic_name_cn', sa.String(), nullable=True),
    sa.Column('comic_name_alt', sa.String(), nullable=True),
    sa.Column('volume_label', sa.String(), nullable=True),
    sa.Column('comic_type', sa.String(), nullable=True),
    sa.Column('is_main_entry', sa.Boolean(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('issue_total', sa.Integer(), nullable=True),
    sa.Column('serialization_status', sa.String(), nullable=True),
    sa.Column('read_order', sa.Float(), nullable=True),
    sa.Column('comicvine_id', sa.Integer(), nullable=True),
    sa.Column('comicvine_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("end_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_comic_end_date_iso'),
    sa.CheckConstraint("media_type = 'comic'", name='ck_comic_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_comic_release_date_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_comic_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_comic_system_id'), 'comic', ['system_id'], unique=False)
    op.create_table('games',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='game', nullable=False),
    sa.Column('game_name_en', sa.String(), nullable=True),
    sa.Column('game_name_cn', sa.String(), nullable=True),
    sa.Column('game_name_roman', sa.String(), nullable=True),
    sa.Column('game_name_jp', sa.String(), nullable=True),
    sa.Column('game_name_alt', sa.String(), nullable=True),
    sa.Column('game_type', sa.String(), nullable=True),
    sa.Column('base_game_id', sa.UUID(), nullable=True),
    sa.Column('completion_level', sa.String(), nullable=True),
    sa.Column('all_endings', sa.Boolean(), nullable=True),
    sa.Column('all_achievements', sa.Boolean(), nullable=True),
    sa.Column('all_collected', sa.Boolean(), nullable=True),
    sa.Column('steam_progress_sync', sa.Boolean(), nullable=True),
    sa.Column('achievements_earned', sa.Integer(), nullable=True),
    sa.Column('achievements_total', sa.Integer(), nullable=True),
    sa.Column('release_status', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('current_patch', sa.String(), nullable=True),
    sa.Column('hours_played', sa.Float(), nullable=True),
    sa.Column('hltb_main', sa.Float(), nullable=True),
    sa.Column('hltb_main_extra', sa.Float(), nullable=True),
    sa.Column('hltb_completionist', sa.Float(), nullable=True),
    sa.Column('price_original_us', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_original_jp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_original_tw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_current_us', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_current_jp', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_current_tw', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('metacritic_score', sa.Integer(), nullable=True),
    sa.Column('metacritic_user_score', sa.Float(), nullable=True),
    sa.Column('igdb_id', sa.Integer(), nullable=True),
    sa.Column('igdb_link', sa.String(), nullable=True),
    sa.Column('steam_appid', sa.Integer(), nullable=True),
    sa.Column('steam_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("game_type <> 'Base Game' OR base_game_id IS NULL", name='ck_games_base_no_parent'),
    sa.CheckConstraint("media_type = 'game'", name='ck_games_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_games_release_date_iso'),
    sa.CheckConstraint('base_game_id IS NULL OR base_game_id <> system_id', name='ck_games_not_self_parent'),
    sa.ForeignKeyConstraint(['base_game_id'], ['games.system_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_games_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_games_system_id'), 'games', ['system_id'], unique=False)
    op.create_table('manga',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='manga', nullable=False),
    sa.Column('manga_name_en', sa.String(), nullable=True),
    sa.Column('manga_name_cn', sa.String(), nullable=True),
    sa.Column('manga_name_roman', sa.String(), nullable=True),
    sa.Column('manga_name_jp', sa.String(), nullable=True),
    sa.Column('manga_name_alt', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('serialization_status', sa.String(), nullable=True),
    sa.Column('vol_total', sa.Integer(), nullable=True),
    sa.Column('ch_total', sa.Integer(), nullable=True),
    sa.Column('mal_rating', sa.Float(), nullable=True),
    sa.Column('mal_rank', sa.String(), nullable=True),
    sa.Column('anilist_rating', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('anime_studio', sa.String(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('mal_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("end_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_manga_end_date_iso'),
    sa.CheckConstraint("media_type = 'manga'", name='ck_manga_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_manga_release_date_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_manga_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_manga_system_id'), 'manga', ['system_id'], unique=False)
    op.create_table('media_content_label',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('label_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['content_label.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('media_id', 'label_id', name='uq_media_content_label_row')
    )
    op.create_index('ix_media_content_label_entry', 'media_content_label', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_content_label_label_id'), 'media_content_label', ['label_id'], unique=False)
    op.create_index(op.f('ix_media_content_label_system_id'), 'media_content_label', ['system_id'], unique=False)
    op.create_table('media_credit',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('studio_id', sa.UUID(), nullable=True),
    sa.Column('publisher_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(person_id, studio_id, publisher_id) = 1', name='ck_media_credit_one_target'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['publisher_id'], ['publisher.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studio_id'], ['studio.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('media_id', 'role', 'person_id', 'studio_id', 'publisher_id', name='uq_media_credit_row', postgresql_nulls_not_distinct=True)
    )
    op.create_index('ix_media_credit_entry', 'media_credit', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_credit_person_id'), 'media_credit', ['person_id'], unique=False)
    op.create_index(op.f('ix_media_credit_publisher_id'), 'media_credit', ['publisher_id'], unique=False)
    op.create_index(op.f('ix_media_credit_role'), 'media_credit', ['role'], unique=False)
    op.create_index(op.f('ix_media_credit_studio_id'), 'media_credit', ['studio_id'], unique=False)
    op.create_index(op.f('ix_media_credit_system_id'), 'media_credit', ['system_id'], unique=False)
    op.create_table('media_source',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('bucket', sa.String(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(option_id, name) = 1', name='ck_media_source_one_target'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['system_option.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('media_id', 'kind', 'bucket', 'option_id', 'name', name='uq_media_source_row', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_media_source_bucket'), 'media_source', ['bucket'], unique=False)
    op.create_index('ix_media_source_entry', 'media_source', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_source_kind'), 'media_source', ['kind'], unique=False)
    op.create_index(op.f('ix_media_source_option_id'), 'media_source', ['option_id'], unique=False)
    op.create_index(op.f('ix_media_source_system_id'), 'media_source', ['system_id'], unique=False)
    op.create_table('media_tag',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['system_option.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('media_id', 'field', 'option_id', name='uq_media_tag_row')
    )
    op.create_index('ix_media_tag_entry', 'media_tag', ['media_id'], unique=False)
    op.create_index(op.f('ix_media_tag_field'), 'media_tag', ['field'], unique=False)
    op.create_index(op.f('ix_media_tag_option_id'), 'media_tag', ['option_id'], unique=False)
    op.create_index(op.f('ix_media_tag_system_id'), 'media_tag', ['system_id'], unique=False)
    op.create_table('movies',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='movie', nullable=False),
    sa.Column('movie_name_en', sa.String(), nullable=True),
    sa.Column('movie_name_cn', sa.String(), nullable=True),
    sa.Column('movie_name_alt', sa.String(), nullable=True),
    sa.Column('airing_status', sa.String(), nullable=True),
    sa.Column('imdb_rating', sa.String(), nullable=True),
    sa.Column('movie_type', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('length_min', sa.Integer(), nullable=True),
    sa.Column('release_date_usa', sa.String(), nullable=True),
    sa.Column('release_date_tw', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('imdb_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("media_type = 'movie'", name='ck_movies_media_type'),
    sa.CheckConstraint("release_date_tw ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_movies_release_date_tw_iso'),
    sa.CheckConstraint("release_date_usa ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_movies_release_date_usa_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_movies_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_movies_system_id'), 'movies', ['system_id'], unique=False)
    op.create_table('note',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('locator', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sort_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(media_id, collection_id, franchise_id, series_id) = 1', name='ck_note_one_owner'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_note_author_id'), 'note', ['author_id'], unique=False)
    op.create_index(op.f('ix_note_collection_id'), 'note', ['collection_id'], unique=False)
    op.create_index(op.f('ix_note_franchise_id'), 'note', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_note_media_id'), 'note', ['media_id'], unique=False)
    op.create_index('ix_note_one_remark_per_owner', 'note', ['media_id', 'collection_id', 'franchise_id', 'series_id', 'author_id'], unique=True, postgresql_nulls_not_distinct=True, postgresql_where=sa.text("section = 'remark'"))
    op.create_index('ix_note_owner_section', 'note', ['media_id', 'collection_id', 'franchise_id', 'series_id', 'section'], unique=False)
    op.create_index(op.f('ix_note_section'), 'note', ['section'], unique=False)
    op.create_index(op.f('ix_note_series_id'), 'note', ['series_id'], unique=False)
    op.create_index(op.f('ix_note_system_id'), 'note', ['system_id'], unique=False)
    op.create_table('novel',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='novel', nullable=False),
    sa.Column('novel_name_en', sa.String(), nullable=True),
    sa.Column('novel_name_cn', sa.String(), nullable=True),
    sa.Column('novel_name_roman', sa.String(), nullable=True),
    sa.Column('novel_name_jp', sa.String(), nullable=True),
    sa.Column('novel_name_alt', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('serialization_status', sa.String(), nullable=True),
    sa.Column('vol_total_original', sa.Float(), nullable=True),
    sa.Column('vol_total_tw', sa.Float(), nullable=True),
    sa.Column('arc_total', sa.Float(), nullable=True),
    sa.Column('ch_total', sa.Float(), nullable=True),
    sa.Column('mal_rating', sa.Float(), nullable=True),
    sa.Column('mal_rank', sa.String(), nullable=True),
    sa.Column('anilist_rating', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.Column('is_main_entry', sa.Boolean(), nullable=True),
    sa.Column('read_order', sa.Float(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('mal_link', sa.String(), nullable=True),
    sa.Column('openlibrary_link', sa.String(), nullable=True),
    sa.Column('openlibrary_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("end_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_novel_end_date_iso'),
    sa.CheckConstraint("media_type = 'novel'", name='ck_novel_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_novel_release_date_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_novel_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_novel_system_id'), 'novel', ['system_id'], unique=False)
    op.create_table('plan_next',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(), server_default='next', nullable=False),
    sa.Column('media_type', sa.String(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(media_id, franchise_id, series_id) = 1', name='ck_plan_next_one_owner'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], name='fk_plan_next_franchise', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_plan_next_media_type', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['series_id'], ['series.system_id'], name='fk_plan_next_series', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_plan_next_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('user_id', 'kind', 'media_type', 'media_id', 'franchise_id', 'series_id', name='uq_plan_next_target', postgresql_nulls_not_distinct=True)
    )
    op.create_index(op.f('ix_plan_next_franchise_id'), 'plan_next', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_plan_next_media_id'), 'plan_next', ['media_id'], unique=False)
    op.create_index(op.f('ix_plan_next_series_id'), 'plan_next', ['series_id'], unique=False)
    op.create_index(op.f('ix_plan_next_system_id'), 'plan_next', ['system_id'], unique=False)
    op.create_index(op.f('ix_plan_next_user_id'), 'plan_next', ['user_id'], unique=False)
    op.create_index('ix_plan_next_user_kind_type', 'plan_next', ['user_id', 'kind', 'media_type'], unique=False)
    op.create_table('quote',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('original_source', sa.String(), nullable=True),
    sa.Column('episode', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('image_file', sa.String(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_general', sa.Boolean(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=True),
    sa.Column('sort_index', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_quote_author_id'), 'quote', ['author_id'], unique=False)
    op.create_index(op.f('ix_quote_media_id'), 'quote', ['media_id'], unique=False)
    op.create_index(op.f('ix_quote_system_id'), 'quote', ['system_id'], unique=False)
    op.create_table('tv_shows',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.String(), server_default='tv-show', nullable=False),
    sa.Column('tv_name_en', sa.String(), nullable=True),
    sa.Column('tv_name_cn', sa.String(), nullable=True),
    sa.Column('tv_name_alt', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('season_part', sa.String(), nullable=True),
    sa.Column('airing_status', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('ep_total', sa.Integer(), nullable=True),
    sa.Column('imdb_rating', sa.String(), nullable=True),
    sa.Column('release_date', sa.String(), nullable=True),
    sa.Column('imdb_id', sa.String(), nullable=True),
    sa.Column('imdb_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("media_type = 'tv-show'", name='ck_tv_shows_media_type'),
    sa.CheckConstraint("release_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_tv_shows_release_date_iso'),
    sa.ForeignKeyConstraint(['system_id', 'media_type'], ['media.system_id', 'media.media_type'], name='fk_tv_shows_media', ondelete='CASCADE', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_tv_shows_system_id'), 'tv_shows', ['system_id'], unique=False)
    op.create_table('user_media_list',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('my_watch_day', sa.String(), nullable=True),
    sa.Column('ep_fin', sa.Integer(), nullable=True),
    sa.Column('vol_fin', sa.Float(), nullable=True),
    sa.Column('vol_fin_page', sa.Integer(), nullable=True),
    sa.Column('ch_fin', sa.Float(), nullable=True),
    sa.Column('arc_fin', sa.Float(), nullable=True),
    sa.Column('ch_fin_in_arc', sa.Float(), nullable=True),
    sa.Column('progress_display', sa.String(), nullable=True),
    sa.Column('issue_fin', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('user_id', 'media_id', name='uq_user_media')
    )
    op.create_index('ix_user_media_list_media', 'user_media_list', ['media_id'], unique=False)
    op.create_index(op.f('ix_user_media_list_system_id'), 'user_media_list', ['system_id'], unique=False)
    op.create_index('ix_user_media_list_user_status', 'user_media_list', ['user_id', 'status'], unique=False)
    op.create_table('watch_order_section',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['watch_order_list.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_watch_order_section_list_id'), 'watch_order_section', ['list_id'], unique=False)
    op.create_index(op.f('ix_watch_order_section_system_id'), 'watch_order_section', ['system_id'], unique=False)
    op.create_table('game_copy',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('game_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storefront', sa.String(), nullable=True),
    sa.Column('ownership', sa.String(), nullable=True),
    sa.Column('copy_format', sa.String(), nullable=True),
    sa.Column('acquisition', sa.String(), nullable=True),
    sa.Column('price_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('price_currency', sa.String(), nullable=True),
    sa.Column('acquired_date', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("acquired_date ~ '^\\d{4}(-\\d{2}(-\\d{2})?)?$'", name='ck_game_copy_acquired_date_iso'),
    sa.ForeignKeyConstraint(['game_id'], ['games.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('user_id', 'game_id', 'storefront', 'copy_format', name='uq_game_copy_row')
    )
    op.create_index('ix_game_copy_game', 'game_copy', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_copy_system_id'), 'game_copy', ['system_id'], unique=False)
    op.create_index(op.f('ix_game_copy_user_id'), 'game_copy', ['user_id'], unique=False)
    op.create_table('meme',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('collection_id', sa.UUID(), nullable=True),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('image_file', sa.String(), nullable=True),
    sa.Column('quote_id', sa.UUID(), nullable=True),
    sa.Column('episode', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('sort_index', sa.Float(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('num_nonnulls(media_id, collection_id, franchise_id, series_id) = 1', name='ck_meme_one_owner'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['quote_id'], ['quote.system_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_meme_author_id'), 'meme', ['author_id'], unique=False)
    op.create_index(op.f('ix_meme_collection_id'), 'meme', ['collection_id'], unique=False)
    op.create_index(op.f('ix_meme_franchise_id'), 'meme', ['franchise_id'], unique=False)
    op.create_index(op.f('ix_meme_media_id'), 'meme', ['media_id'], unique=False)
    op.create_index(op.f('ix_meme_quote_id'), 'meme', ['quote_id'], unique=True)
    op.create_index(op.f('ix_meme_series_id'), 'meme', ['series_id'], unique=False)
    op.create_index(op.f('ix_meme_system_id'), 'meme', ['system_id'], unique=False)
    op.create_table('novel_unit',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('novel_id', sa.UUID(), nullable=False),
    sa.Column('unit_kind', sa.String(), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('unit_key', sa.String(), nullable=True),
    sa.Column('name_cn', sa.String(), nullable=True),
    sa.Column('name_en', sa.String(), nullable=True),
    sa.Column('remark', sa.String(), nullable=True),
    sa.Column('ch_count', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("unit_kind = 'arc' OR ch_count IS NULL", name='ck_novel_unit_ch_count_arc_only'),
    sa.CheckConstraint("unit_kind IN ('volume','arc','story','chapter')", name='ck_novel_unit_kind'),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.system_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_novel_unit_novel_id'), 'novel_unit', ['novel_id'], unique=False)
    op.create_index('ix_novel_unit_novel_kind_position', 'novel_unit', ['novel_id', 'unit_kind', 'position'], unique=False)
    op.create_index(op.f('ix_novel_unit_system_id'), 'novel_unit', ['system_id'], unique=False)
    op.create_table('watch_order_item',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('list_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('section_id', sa.UUID(), nullable=True),
    sa.Column('ep_start', sa.Integer(), nullable=True),
    sa.Column('ep_end', sa.Integer(), nullable=True),
    sa.Column('importance', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['watch_order_list.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['watch_order_section.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_watch_order_item_list_id'), 'watch_order_item', ['list_id'], unique=False)
    op.create_index(op.f('ix_watch_order_item_media_id'), 'watch_order_item', ['media_id'], unique=False)
    op.create_index(op.f('ix_watch_order_item_section_id'), 'watch_order_item', ['section_id'], unique=False)
    op.create_index(op.f('ix_watch_order_item_system_id'), 'watch_order_item', ['system_id'], unique=False)
    op.create_table('user_novel_unit_rating',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=False),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['novel_unit.system_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id'),
    sa.UniqueConstraint('user_id', 'unit_id', name='uq_user_novel_unit')
    )
    op.create_index(op.f('ix_user_novel_unit_rating_system_id'), 'user_novel_unit_rating', ['system_id'], unique=False)
    op.create_index(op.f('ix_user_novel_unit_rating_unit_id'), 'user_novel_unit_rating', ['unit_id'], unique=False)
    op.create_index(op.f('ix_user_novel_unit_rating_user_id'), 'user_novel_unit_rating', ['user_id'], unique=False)
    # ### end Alembic commands ###

    for name in SEQUENCES:
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {name}")

    # collection.cover_franchise_id -> franchise, a CIRCULAR foreign key that
    # is declared use_alter=True so create_all/drop_all can order the DDL.
    # SQLAlchemy OMITS such a constraint from CREATE TABLE and expects
    # metadata.create_all() to schedule a separate ALTER - which op.create_table
    # does not do, so the ForeignKeyConstraint autogenerate wrote into the
    # create_table() call above is silently a no-op. It is added here instead.
    op.create_foreign_key(
        "fk_collection_cover_franchise_id",
        "collection",
        "franchise",
        ["cover_franchise_id"],
        ["system_id"],
        ondelete="SET NULL",
    )

    op.execute(DELETE_MEDIA_FUNCTION)
    for table in MEDIA_TABLES:
        op.execute(
            f"CREATE TRIGGER trg_{table}_delete_media "
            f"AFTER DELETE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION delete_media_row()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    for table in MEDIA_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_delete_media ON {table}")
    op.execute("DROP FUNCTION IF EXISTS delete_media_row()")
    op.drop_constraint(
        "fk_collection_cover_franchise_id", "collection", type_="foreignkey"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_novel_unit_rating_user_id'), table_name='user_novel_unit_rating')
    op.drop_index(op.f('ix_user_novel_unit_rating_unit_id'), table_name='user_novel_unit_rating')
    op.drop_index(op.f('ix_user_novel_unit_rating_system_id'), table_name='user_novel_unit_rating')
    op.drop_table('user_novel_unit_rating')
    op.drop_index(op.f('ix_watch_order_item_system_id'), table_name='watch_order_item')
    op.drop_index(op.f('ix_watch_order_item_section_id'), table_name='watch_order_item')
    op.drop_index(op.f('ix_watch_order_item_media_id'), table_name='watch_order_item')
    op.drop_index(op.f('ix_watch_order_item_list_id'), table_name='watch_order_item')
    op.drop_table('watch_order_item')
    op.drop_index(op.f('ix_novel_unit_system_id'), table_name='novel_unit')
    op.drop_index('ix_novel_unit_novel_kind_position', table_name='novel_unit')
    op.drop_index(op.f('ix_novel_unit_novel_id'), table_name='novel_unit')
    op.drop_table('novel_unit')
    op.drop_index(op.f('ix_meme_system_id'), table_name='meme')
    op.drop_index(op.f('ix_meme_series_id'), table_name='meme')
    op.drop_index(op.f('ix_meme_quote_id'), table_name='meme')
    op.drop_index(op.f('ix_meme_media_id'), table_name='meme')
    op.drop_index(op.f('ix_meme_franchise_id'), table_name='meme')
    op.drop_index(op.f('ix_meme_collection_id'), table_name='meme')
    op.drop_index(op.f('ix_meme_author_id'), table_name='meme')
    op.drop_table('meme')
    op.drop_index(op.f('ix_game_copy_user_id'), table_name='game_copy')
    op.drop_index(op.f('ix_game_copy_system_id'), table_name='game_copy')
    op.drop_index('ix_game_copy_game', table_name='game_copy')
    op.drop_table('game_copy')
    op.drop_index(op.f('ix_watch_order_section_system_id'), table_name='watch_order_section')
    op.drop_index(op.f('ix_watch_order_section_list_id'), table_name='watch_order_section')
    op.drop_table('watch_order_section')
    op.drop_index('ix_user_media_list_user_status', table_name='user_media_list')
    op.drop_index(op.f('ix_user_media_list_system_id'), table_name='user_media_list')
    op.drop_index('ix_user_media_list_media', table_name='user_media_list')
    op.drop_table('user_media_list')
    op.drop_index(op.f('ix_tv_shows_system_id'), table_name='tv_shows')
    op.drop_table('tv_shows')
    op.drop_index(op.f('ix_quote_system_id'), table_name='quote')
    op.drop_index(op.f('ix_quote_media_id'), table_name='quote')
    op.drop_index(op.f('ix_quote_author_id'), table_name='quote')
    op.drop_table('quote')
    op.drop_index('ix_plan_next_user_kind_type', table_name='plan_next')
    op.drop_index(op.f('ix_plan_next_user_id'), table_name='plan_next')
    op.drop_index(op.f('ix_plan_next_system_id'), table_name='plan_next')
    op.drop_index(op.f('ix_plan_next_series_id'), table_name='plan_next')
    op.drop_index(op.f('ix_plan_next_media_id'), table_name='plan_next')
    op.drop_index(op.f('ix_plan_next_franchise_id'), table_name='plan_next')
    op.drop_table('plan_next')
    op.drop_index(op.f('ix_novel_system_id'), table_name='novel')
    op.drop_table('novel')
    op.drop_index(op.f('ix_note_system_id'), table_name='note')
    op.drop_index(op.f('ix_note_series_id'), table_name='note')
    op.drop_index(op.f('ix_note_section'), table_name='note')
    op.drop_index('ix_note_owner_section', table_name='note')
    op.drop_index('ix_note_one_remark_per_owner', table_name='note', postgresql_nulls_not_distinct=True, postgresql_where=sa.text("section = 'remark'"))
    op.drop_index(op.f('ix_note_media_id'), table_name='note')
    op.drop_index(op.f('ix_note_franchise_id'), table_name='note')
    op.drop_index(op.f('ix_note_collection_id'), table_name='note')
    op.drop_index(op.f('ix_note_author_id'), table_name='note')
    op.drop_table('note')
    op.drop_index(op.f('ix_movies_system_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_media_tag_system_id'), table_name='media_tag')
    op.drop_index(op.f('ix_media_tag_option_id'), table_name='media_tag')
    op.drop_index(op.f('ix_media_tag_field'), table_name='media_tag')
    op.drop_index('ix_media_tag_entry', table_name='media_tag')
    op.drop_table('media_tag')
    op.drop_index(op.f('ix_media_source_system_id'), table_name='media_source')
    op.drop_index(op.f('ix_media_source_option_id'), table_name='media_source')
    op.drop_index(op.f('ix_media_source_kind'), table_name='media_source')
    op.drop_index('ix_media_source_entry', table_name='media_source')
    op.drop_index(op.f('ix_media_source_bucket'), table_name='media_source')
    op.drop_table('media_source')
    op.drop_index(op.f('ix_media_credit_system_id'), table_name='media_credit')
    op.drop_index(op.f('ix_media_credit_studio_id'), table_name='media_credit')
    op.drop_index(op.f('ix_media_credit_role'), table_name='media_credit')
    op.drop_index(op.f('ix_media_credit_publisher_id'), table_name='media_credit')
    op.drop_index(op.f('ix_media_credit_person_id'), table_name='media_credit')
    op.drop_index('ix_media_credit_entry', table_name='media_credit')
    op.drop_table('media_credit')
    op.drop_index(op.f('ix_media_content_label_system_id'), table_name='media_content_label')
    op.drop_index(op.f('ix_media_content_label_label_id'), table_name='media_content_label')
    op.drop_index('ix_media_content_label_entry', table_name='media_content_label')
    op.drop_table('media_content_label')
    op.drop_index(op.f('ix_manga_system_id'), table_name='manga')
    op.drop_table('manga')
    op.drop_index(op.f('ix_games_system_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_comic_system_id'), table_name='comic')
    op.drop_table('comic')
    op.drop_index(op.f('ix_cartoons_system_id'), table_name='cartoons')
    op.drop_table('cartoons')
    op.drop_index(op.f('ix_anime_movies_system_id'), table_name='anime_movies')
    op.drop_table('anime_movies')
    op.drop_index(op.f('ix_anime_system_id'), table_name='anime')
    op.drop_table('anime')
    op.drop_index(op.f('ix_watch_order_list_system_id'), table_name='watch_order_list')
    op.drop_index(op.f('ix_watch_order_list_series_id'), table_name='watch_order_list')
    op.drop_index(op.f('ix_watch_order_list_franchise_id'), table_name='watch_order_list')
    op.drop_index(op.f('ix_watch_order_list_collection_id'), table_name='watch_order_list')
    op.drop_table('watch_order_list')
    op.drop_index(op.f('ix_user_access_mode_denial_user_access_mode_id'), table_name='user_access_mode_denial')
    op.drop_index(op.f('ix_user_access_mode_denial_system_id'), table_name='user_access_mode_denial')
    op.drop_table('user_access_mode_denial')
    op.drop_index(op.f('ix_media_system_id'), table_name='media')
    op.drop_index(op.f('ix_media_media_type'), table_name='media')
    op.drop_index(op.f('ix_media_display_name'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_user_access_mode_user_id'), table_name='user_access_mode')
    op.drop_index(op.f('ix_user_access_mode_system_id'), table_name='user_access_mode')
    op.drop_index(op.f('ix_user_access_mode_mode_id'), table_name='user_access_mode')
    op.drop_index('ix_one_default_mode_per_user', table_name='user_access_mode', postgresql_where=sa.text('is_default'))
    op.drop_table('user_access_mode')
    op.drop_index(op.f('ix_series_system_id'), table_name='series')
    op.drop_table('series')
    op.drop_index(op.f('ix_seasonal_seasonal'), table_name='seasonal')
    op.drop_table('seasonal')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('ix_one_installation_owner', table_name='users', postgresql_where=sa.text('is_installation_owner'))
    op.drop_table('users')
    op.drop_index(op.f('ix_system_option_usage_option_id'), table_name='system_option_usage')
    op.drop_table('system_option_usage')
    op.drop_index(op.f('ix_system_option_scope_option_id'), table_name='system_option_scope')
    op.drop_table('system_option_scope')
    op.drop_index(op.f('ix_system_option_alias_option_id'), table_name='system_option_alias')
    op.drop_index('ix_system_option_alias_lookup', table_name='system_option_alias')
    op.drop_table('system_option_alias')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_publisher_scope_publisher_id'), table_name='publisher_scope')
    op.drop_table('publisher_scope')
    op.drop_index(op.f('ix_person_role_role'), table_name='person_role')
    op.drop_index(op.f('ix_person_role_person_id'), table_name='person_role')
    op.drop_table('person_role')
    op.drop_index(op.f('ix_franchise_system_id'), table_name='franchise')
    op.drop_index(op.f('ix_franchise_collection_id'), table_name='franchise')
    op.drop_table('franchise')
    op.drop_index(op.f('ix_character_casting_system_id'), table_name='character_casting')
    op.drop_index(op.f('ix_character_casting_person_id'), table_name='character_casting')
    op.drop_index('ix_character_casting_entry', table_name='character_casting')
    op.drop_index(op.f('ix_character_casting_character_id'), table_name='character_casting')
    op.drop_table('character_casting')
    op.drop_index(op.f('ix_access_mode_label_system_id'), table_name='access_mode_label')
    op.drop_index(op.f('ix_access_mode_label_mode_id'), table_name='access_mode_label')
    op.drop_index(op.f('ix_access_mode_label_label_id'), table_name='access_mode_label')
    op.drop_table('access_mode_label')
    op.drop_index(op.f('ix_access_mode_field_group_system_id'), table_name='access_mode_field_group')
    op.drop_index(op.f('ix_access_mode_field_group_mode_id'), table_name='access_mode_field_group')
    op.drop_table('access_mode_field_group')
    op.drop_index(op.f('ix_system_option_system_id'), table_name='system_option')
    op.drop_index(op.f('ix_system_option_category'), table_name='system_option')
    op.drop_table('system_option')
    op.drop_index(op.f('ix_system_configs_id'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_config_key'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_studio_system_id'), table_name='studio')
    op.drop_index(op.f('ix_studio_name_en'), table_name='studio')
    op.drop_table('studio')
    op.drop_index(op.f('ix_role_system_id'), table_name='role')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_publisher_system_id'), table_name='publisher')
    op.drop_index(op.f('ix_publisher_name_en'), table_name='publisher')
    op.drop_table('publisher')
    op.drop_index(op.f('ix_person_system_id'), table_name='person')
    op.drop_index(op.f('ix_person_name_en'), table_name='person')
    op.drop_table('person')
    op.drop_index('ix_media_relation_to', table_name='media_relation')
    op.drop_index(op.f('ix_media_relation_system_id'), table_name='media_relation')
    op.drop_index('ix_media_relation_from', table_name='media_relation')
    op.drop_table('media_relation')
    op.drop_index(op.f('ix_deleted_record_id'), table_name='deleted_record')
    op.drop_table('deleted_record')
    op.drop_index(op.f('ix_data_control_logs_id'), table_name='data_control_logs')
    op.drop_table('data_control_logs')
    op.drop_index(op.f('ix_content_label_system_id'), table_name='content_label')
    op.drop_index(op.f('ix_content_label_key'), table_name='content_label')
    op.drop_table('content_label')
    op.drop_index(op.f('ix_collection_system_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_character_system_id'), table_name='character')
    op.drop_index(op.f('ix_character_name_en'), table_name='character')
    op.drop_table('character')
    op.drop_index(op.f('ix_access_mode_system_id'), table_name='access_mode')
    op.drop_index(op.f('ix_access_mode_key'), table_name='access_mode')
    op.drop_table('access_mode')
    # ### end Alembic commands ###

    for name in SEQUENCES:
        op.execute(f"DROP SEQUENCE IF EXISTS {name}")
