"""add cartoons table with imdb_rating

Revision ID: 4badc000f3c6
Revises: 8ebb04663811
Create Date: 2026-04-30 13:40:06.840423

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4badc000f3c6"
down_revision: Union[str, Sequence[str], None] = "8ebb04663811"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cartoons",
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("franchise_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("cartoon_name_en", sa.String(), nullable=True),
        sa.Column("cartoon_name_cn", sa.String(), nullable=True),
        sa.Column("cartoon_name_alt", sa.String(), nullable=True),
        sa.Column("season_part", sa.String(), nullable=True),
        sa.Column("source_official", sa.String(), nullable=True),
        sa.Column("airing_type", sa.String(), nullable=True),
        sa.Column("airing_status", sa.String(), nullable=True),
        sa.Column("watching_status", sa.String(), nullable=False),
        sa.Column("is_main", sa.String(), nullable=True),
        sa.Column("ep_total", sa.Integer(), nullable=True),
        sa.Column("ep_fin", sa.Integer(), nullable=True),
        sa.Column("length_ep_min", sa.Integer(), nullable=True),
        sa.Column("my_rating", sa.String(), nullable=True),
        sa.Column("imdb_rating", sa.String(), nullable=True),
        sa.Column("release_date", sa.String(), nullable=True),
        sa.Column("derive_related", sa.Boolean(), nullable=True),
        sa.Column("prequel_id", sa.UUID(), nullable=True),
        sa.Column("sequel_id", sa.UUID(), nullable=True),
        sa.Column("watch_order", sa.Float(), nullable=True),
        sa.Column("imdb_id", sa.String(), nullable=True),
        sa.Column("imdb_link", sa.String(), nullable=True),
        sa.Column(
            "source_other", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("watch_next", sa.Boolean(), nullable=True),
        sa.Column("to_rewatch", sa.Boolean(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cover_image_file", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["franchise_id"], ["franchise.system_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["series_id"], ["series.system_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("system_id"),
    )
    op.create_index(
        op.f("ix_cartoons_system_id"), "cartoons", ["system_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cartoons_system_id"), table_name="cartoons")
    op.drop_table("cartoons")
    # ### end Alembic commands ###
