"""clean_v2_baseline

Revision ID: 708e4a1a76c5
Revises: aa47482dcc6c
Create Date: 2026-03-14 17:36:19.329442

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "708e4a1a76c5"
down_revision: Union[str, Sequence[str], None] = "aa47482dcc6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Handle Column Type Changes with PostgreSQL Casting
    # Altering remark to Text
    op.alter_column(
        "anime_entries",
        "remark",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )

    # FIXED: mal_id casting from VARCHAR to Integer using explicit cast
    op.alter_column(
        "anime_entries",
        "mal_id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="mal_id::integer",
    )

    # Altering seiyuu to Text
    op.alter_column(
        "anime_entries",
        "seiyuu",
        existing_type=sa.VARCHAR(),
        type_=sa.Text(),
        existing_nullable=True,
    )

    # 2. Resilient Drop Columns (Handling UndefinedColumn errors)
    # Using if_exists=True to prevent crashes if columns were already removed
    op.drop_column("anime_entries", "distributor_tw", if_exists=True)
    op.drop_column("anime_entries", "mal_rank", if_exists=True)
    op.drop_column("anime_entries", "producer", if_exists=True)
    op.drop_column("anime_entries", "studio", if_exists=True)
    op.drop_column("anime_entries", "director", if_exists=True)

    # Clean up anime_series table metadata columns
    op.drop_column("anime_series", "series_description", if_exists=True)
    op.drop_column("anime_series", "anilist_link", if_exists=True)
    op.drop_column("anime_series", "mal_link", if_exists=True)
    op.drop_column("anime_series", "mal_id", if_exists=True)
    op.drop_column("anime_series", "genre_sub", if_exists=True)
    op.drop_column("anime_series", "genre_main", if_exists=True)
    op.drop_column("anime_series", "status", if_exists=True)

    # 3. Add V2 columns to anime_entries with correct types
    op.add_column(
        "anime_entries",
        sa.Column("mal_rank", sa.Integer(), nullable=True),
    )
    op.add_column(
        "anime_entries",
        sa.Column("director", sa.String(), nullable=True),
    )
    op.add_column(
        "anime_entries",
        sa.Column("studio", sa.String(), nullable=True),
    )
    op.add_column(
        "anime_entries",
        sa.Column("producer", sa.String(), nullable=True),
    )
    op.add_column(
        "anime_entries",
        sa.Column("distributor_tw", sa.String(), nullable=True),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Re-add columns to anime_series
    op.add_column("anime_series", sa.Column("status", sa.VARCHAR(), nullable=True))
    op.add_column("anime_series", sa.Column("genre_main", sa.VARCHAR(), nullable=True))
    op.add_column("anime_series", sa.Column("genre_sub", sa.VARCHAR(), nullable=True))
    op.add_column("anime_series", sa.Column("mal_id", sa.INTEGER(), nullable=True))
    op.add_column("anime_series", sa.Column("mal_link", sa.VARCHAR(), nullable=True))
    op.add_column(
        "anime_series", sa.Column("anilist_link", sa.VARCHAR(), nullable=True)
    )
    op.add_column(
        "anime_series", sa.Column("series_description", sa.TEXT(), nullable=True)
    )

    # Remove V2 columns from anime_entries
    op.drop_column("anime_entries", "distributor_tw")
    op.drop_column("anime_entries", "producer")
    op.drop_column("anime_entries", "studio")
    op.drop_column("anime_entries", "director")
    op.drop_column("anime_entries", "mal_rank")

    # Re-add V1 columns
    op.add_column("anime_entries", sa.Column("director", sa.VARCHAR(), nullable=True))
    op.add_column("anime_entries", sa.Column("producer", sa.VARCHAR(), nullable=True))
    op.add_column("anime_entries", sa.Column("studio", sa.VARCHAR(), nullable=True))
    op.add_column("anime_entries", sa.Column("mal_rank", sa.VARCHAR(), nullable=True))
    op.add_column(
        "anime_entries", sa.Column("distributor_tw", sa.VARCHAR(), nullable=True)
    )

    # Revert type changes
    op.alter_column(
        "anime_entries",
        "seiyuu",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "anime_entries",
        "mal_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    op.alter_column(
        "anime_entries",
        "remark",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
