"""initial_migration

Revision ID: 86982d71c2f1
Revises:
Create Date: 2026-04-12 19:49:15.125719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86982d71c2f1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Use a try block to ignore errors if the constraint is already gone
    try:
        op.drop_constraint(op.f("seasonal_seasonal_key"), "seasonal", type_="unique")
    except Exception:
        print("Constraint 'seasonal_seasonal_key' not found, skipping...")

    try:
        op.create_index(
            op.f("ix_seasonal_seasonal"), "seasonal", ["seasonal"], unique=True
        )
    except Exception:
        print("Index 'ix_seasonal_seasonal' already exists, skipping...")

    try:
        op.drop_constraint(
            op.f("system_configs_config_key_key"), "system_configs", type_="unique"
        )
    except Exception:
        print("Constraint 'system_configs_config_key_key' not found, skipping...")

    try:
        op.create_index(
            op.f("ix_system_configs_config_key"),
            "system_configs",
            ["config_key"],
            unique=True,
        )
    except Exception:
        print("Index 'ix_system_configs_config_key' already exists, skipping...")

    try:
        op.create_index(
            op.f("ix_system_configs_id"), "system_configs", ["id"], unique=False
        )
    except Exception:
        print("Index 'ix_system_configs_id' already exists, skipping...")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_system_configs_id"), table_name="system_configs")
    op.drop_index(op.f("ix_system_configs_config_key"), table_name="system_configs")
    op.create_unique_constraint(
        op.f("system_configs_config_key_key"),
        "system_configs",
        ["config_key"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_seasonal_seasonal"), table_name="seasonal")
    op.create_unique_constraint(
        op.f("seasonal_seasonal_key"),
        "seasonal",
        ["seasonal"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
