"""clean_v2_baseline

Revision ID: aa47482dcc6c
Revises: 639f52e4acb5
Create Date: 2026-03-14 17:04:25.366054

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa47482dcc6c"
down_revision: Union[str, Sequence[str], None] = "639f52e4acb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Modify the alter_column line to include the postgresql_using parameter
    op.alter_column(
        "anime_entries",
        "mal_rating",
        existing_type=sa.VARCHAR(),
        type_=sa.Float(),
        existing_nullable=True,
        postgresql_using="NULLIF(mal_rating, '')::double precision",
    )  # This handles empty strings safely


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anime_entries",
        "mal_rating",
        existing_type=sa.Float(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
