"""update source_other column using jsonb for anime table

Revision ID: b1423952d9af
Revises: f6a7b8c9d0e1
Create Date: 2026-04-22 13:43:49.374369

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1423952d9af"
down_revision: Union[str, Sequence[str], None] = "f6a7b8c9d0e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "anime",
        "source_other",
        existing_type=sa.VARCHAR(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
    )
    op.drop_column("anime", "source_other_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "anime",
        sa.Column(
            "source_other_link", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "anime",
        "source_other",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )


# ### end Alembic commands ###
