"""add novel table

Revision ID: df0d6478d558
Revises: 7ec2ef0fced2
Create Date: 2026-05-12 22:19:24.888757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df0d6478d558'
down_revision: Union[str, Sequence[str], None] = '7ec2ef0fced2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel',
    sa.Column('system_id', sa.UUID(), nullable=False),
    sa.Column('franchise_id', sa.UUID(), nullable=True),
    sa.Column('series_id', sa.UUID(), nullable=True),
    sa.Column('novel_name_en', sa.String(), nullable=True),
    sa.Column('novel_name_cn', sa.String(), nullable=True),
    sa.Column('novel_name_roman', sa.String(), nullable=True),
    sa.Column('novel_name_jp', sa.String(), nullable=True),
    sa.Column('novel_name_alt', sa.String(), nullable=True),
    sa.Column('novel_name_each_cn', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('novel_name_each_en', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('is_main', sa.String(), nullable=True),
    sa.Column('serialization_status', sa.String(), nullable=True),
    sa.Column('reading_status', sa.String(), nullable=False),
    sa.Column('vol_total_original', sa.Float(), nullable=True),
    sa.Column('vol_total_tw', sa.Float(), nullable=True),
    sa.Column('vol_fin', sa.Float(), nullable=False),
    sa.Column('arc_total', sa.Float(), nullable=True),
    sa.Column('arc_fin', sa.Float(), nullable=False),
    sa.Column('ch_total', sa.Float(), nullable=True),
    sa.Column('ch_fin', sa.Float(), nullable=False),
    sa.Column('progress_display', sa.String(), nullable=True),
    sa.Column('my_rating', sa.String(), nullable=True),
    sa.Column('mal_rating', sa.Float(), nullable=True),
    sa.Column('mal_rank', sa.String(), nullable=True),
    sa.Column('anilist_rating', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('illustrator', sa.String(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('publisher_tw', sa.String(), nullable=True),
    sa.Column('prequel_id', sa.UUID(), nullable=True),
    sa.Column('sequel_id', sa.UUID(), nullable=True),
    sa.Column('is_main_entry', sa.Boolean(), nullable=True),
    sa.Column('read_order', sa.Float(), nullable=True),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('mal_link', sa.String(), nullable=True),
    sa.Column('anilist_link', sa.String(), nullable=True),
    sa.Column('source_other', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('read_next', sa.Boolean(), nullable=True),
    sa.Column('to_reread', sa.Boolean(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_image_file', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['franchise_id'], ['franchise.system_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['series_id'], ['series.system_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('system_id')
    )
    op.create_index(op.f('ix_novel_system_id'), 'novel', ['system_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_novel_system_id'), table_name='novel')
    op.drop_table('novel')
    # ### end Alembic commands ###
