"""add watch_next_group to franchise

Revision ID: e20cf35a6d03
Revises: e53735cf60dc
Create Date: 2026-04-17 10:00:30.780406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20cf35a6d03'
down_revision: Union[str, Sequence[str], None] = 'e53735cf60dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchise', sa.Column('watch_next_group', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('franchise', 'watch_next_group')
    # ### end Alembic commands ###
