"""app.services.domain package — business logic split by concern.

Re-exports every public function so callers can import from the package
root regardless of which concern module a function lives in.
"""

from app.services.domain.hierarchy import (
    resolve_series_parent_hierarchy,
    resolve_anime_parent_hierarchy,
    resolve_anime_movie_parent_hierarchy,
    resolve_movie_parent_hierarchy,
    resolve_tv_show_parent_hierarchy,
    resolve_cartoon_parent_hierarchy,
    resolve_manga_parent_hierarchy,
    resolve_novel_parent_hierarchy,
)

from app.services.domain.watch_order import (
    MEDIA_TYPE_MODELS,
    VALID_WATCH_ORDER_MEDIA_TYPES,
    resolve_items,
    list_candidate_entries,
    entry_exists,
    get_entry_franchise_id,
)

from app.services.domain.checking import (
    apply_validate_episode_math,
    apply_validate_vol_math,
    apply_validate_ch_math,
    has_missing_values_anime,
    has_missing_values_anime_movie,
    has_missing_values_movie,
    has_missing_values_tv_show,
    has_missing_values_cartoon,
    has_missing_values_manga,
    has_missing_values_novel,
    apply_check_baha,
)

from app.services.domain.completion import (
    check_is_tv_completed,
    check_is_movie_completed,
    check_is_reading_completed,
    mark_tv_completed,
    mark_movie_completed,
    mark_reading_completed,
    mark_novel_completed,
    apply_completion_timestamp,
)

from app.services.domain.remarks import (
    find_all_remarks,
)

from app.services.domain.duplicates import (
    find_duplicate_franchises,
    find_duplicate_series,
    find_duplicate_anime,
    find_duplicate_system_options,
    find_duplicate_anime_movie,
    find_duplicate_movie,
    find_duplicate_tv_show,
    find_duplicate_cartoon,
    find_duplicate_manga,
    find_duplicate_novel,
    find_all_duplicates,
)

from app.services.domain.derivation import (
    apply_extract_mal_id_anime,
    apply_extract_mal_id_manga_novel,
    apply_extract_imdb_id,
    apply_extract_season_from_title,
    apply_calculate_seasonal_from_month,
    derive_watch_order_anime,
    derive_watch_order_tv_show,
    derive_watch_order_cartoon,
    derive_prequel_sequel_anime,
    derive_prequel_sequel_tv_show,
    derive_prequel_sequel_cartoon,
    derive_prequel_sequel_manga,
    derive_ep_previous_anime,
    derive_season_1_anime,
    derive_season_1_tv_show,
    derive_season_1_cartoon,
)

from app.services.domain.autofill import (
    autofill_anime_from_mal,
    autofill_anime_movie_from_mal,
    autofill_manga_from_mal,
    autofill_novel_from_mal,
    autofill_movie_from_imdb,
    autofill_tv_show_from_imdb,
    autofill_cartoon_from_imdb,
)

from app.services.domain.seasonal import (
    create_missing_seasonal,
    sync_seasonal_counts,
)

from app.services.domain.options_extraction import (
    extract_system_options_from_anime,
    extract_system_options_from_anime_movie,
    extract_system_options_from_tv_show,
    extract_system_options_from_cartoon,
    extract_system_options_from_manga,
    extract_system_options_from_novel,
)

from app.services.domain.post_processing import (
    apply_single_replace_anime,
    apply_single_replace_anime_movie,
    apply_single_replace_movie,
    apply_single_replace_tv_show,
    apply_single_replace_cartoon,
    apply_single_replace_manga,
    apply_single_replace_novel,
    anime_post_processing,
    anime_movie_post_processing,
    tv_show_post_processing,
    cartoon_post_processing,
    manga_post_processing,
    derive_related_anime,
    derive_related_tv_show,
    derive_related_cartoon,
    derive_related_manga,
)

__all__ = [
    "resolve_series_parent_hierarchy",
    "resolve_anime_parent_hierarchy",
    "resolve_anime_movie_parent_hierarchy",
    "resolve_movie_parent_hierarchy",
    "resolve_tv_show_parent_hierarchy",
    "resolve_cartoon_parent_hierarchy",
    "resolve_manga_parent_hierarchy",
    "resolve_novel_parent_hierarchy",
    "apply_validate_episode_math",
    "apply_validate_vol_math",
    "apply_validate_ch_math",
    "has_missing_values_anime",
    "has_missing_values_anime_movie",
    "has_missing_values_movie",
    "has_missing_values_tv_show",
    "has_missing_values_cartoon",
    "has_missing_values_manga",
    "has_missing_values_novel",
    "apply_check_baha",
    "check_is_tv_completed",
    "check_is_movie_completed",
    "check_is_reading_completed",
    "mark_tv_completed",
    "mark_movie_completed",
    "mark_reading_completed",
    "mark_novel_completed",
    "apply_completion_timestamp",
    "find_all_remarks",
    "find_duplicate_franchises",
    "find_duplicate_series",
    "find_duplicate_anime",
    "find_duplicate_system_options",
    "find_duplicate_anime_movie",
    "find_duplicate_movie",
    "find_duplicate_tv_show",
    "find_duplicate_cartoon",
    "find_duplicate_manga",
    "find_duplicate_novel",
    "find_all_duplicates",
    "apply_extract_mal_id_anime",
    "apply_extract_mal_id_manga_novel",
    "apply_extract_imdb_id",
    "apply_extract_season_from_title",
    "apply_calculate_seasonal_from_month",
    "MEDIA_TYPE_MODELS",
    "VALID_WATCH_ORDER_MEDIA_TYPES",
    "resolve_items",
    "list_candidate_entries",
    "entry_exists",
    "get_entry_franchise_id",
    "derive_watch_order_anime",
    "derive_watch_order_tv_show",
    "derive_watch_order_cartoon",
    "derive_prequel_sequel_anime",
    "derive_prequel_sequel_tv_show",
    "derive_prequel_sequel_cartoon",
    "derive_prequel_sequel_manga",
    "derive_ep_previous_anime",
    "derive_season_1_anime",
    "derive_season_1_tv_show",
    "derive_season_1_cartoon",
    "autofill_anime_from_mal",
    "autofill_anime_movie_from_mal",
    "autofill_manga_from_mal",
    "autofill_novel_from_mal",
    "autofill_movie_from_imdb",
    "autofill_tv_show_from_imdb",
    "autofill_cartoon_from_imdb",
    "create_missing_seasonal",
    "sync_seasonal_counts",
    "extract_system_options_from_anime",
    "extract_system_options_from_anime_movie",
    "extract_system_options_from_tv_show",
    "extract_system_options_from_cartoon",
    "extract_system_options_from_manga",
    "extract_system_options_from_novel",
    "apply_single_replace_anime",
    "apply_single_replace_anime_movie",
    "apply_single_replace_movie",
    "apply_single_replace_tv_show",
    "apply_single_replace_cartoon",
    "apply_single_replace_manga",
    "apply_single_replace_novel",
    "anime_post_processing",
    "anime_movie_post_processing",
    "tv_show_post_processing",
    "cartoon_post_processing",
    "manga_post_processing",
    "derive_related_anime",
    "derive_related_tv_show",
    "derive_related_cartoon",
    "derive_related_manga",
]
