// Blank-form factories for every Add-page media type.
//
// These live in config/ rather than in the add-tab components so that other
// config modules (the form-field registry) can derive field keys from them
// without importing page-level JSX. Each add-tab re-exports its own factory,
// so existing `import AnimeAddTab, { defaultAnime }` imports keep working.
//
// Values here are the BUILT-IN baseline. Admin-configured overrides from
// /api/form-defaults are layered on top by resolveDefaults() in
// hooks/useFormDefaults.js -- these factories are what the app falls back to
// when nothing is configured or the fetch fails.

export const defaultAnime = () => ({
  anime_name_en: "",
  anime_name_cn: "",
  anime_name_roman: "",
  anime_name_jp: "",
  anime_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  season_num: "",
  part_num: "",
  airing_type: "",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  is_main: "本傳",
  ep_previous: "",
  ep_total: "",
  ep_fin: "",
  ep_special: "",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  release_season: "",
  release_month: "",
  release_year: "",
  broadcast_day: "",
  broadcast_time: "",
  my_watch_day: "",
  genre_main: "",
  genre_sub: "",
  studio: "",
  director: "",
  producer: "",
  music: "",
  distributor_tw: "",
  prequel_id: null,
  sequel_id: null,
  alternative: "",
  is_main_entry: false,
  watch_order: "",
  derive_related: "",
  mal_id: "",
  mal_link: "",
  anilist_link: "",
  official_link: "",
  twitter_link: "",
  source_baha: "",
  baha_link: "",
  source_netflix: "",
  source_other: [],
  op: "",
  ed: "",
  insert_ost: "",
  seiyuu: "",
  cover_image_file: "",
  remark: "",
});

export const defaultAnimeMovie = () => ({
  anime_movie_name_en: "",
  anime_movie_name_cn: "",
  anime_movie_name_roman: "",
  anime_movie_name_jp: "",
  anime_movie_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  release_date_jp: "",
  release_date_tw: "",
  length_min: "",
  studio: "",
  director: "",
  mal_id: "",
  mal_link: "",
  anilist_link: "",
  official_link: "",
  twitter_link: "",
  source_baha: "",
  baha_link: "",
  source_netflix: "",
  source_other: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultMovie = () => ({
  movie_name_en: "",
  movie_name_cn: "",
  movie_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  airing_status: "Finished Airing",
  watching_status: "Might Watch",
  my_rating: "",
  movie_type: "Reality",
  is_main: "本傳",
  length_min: "",
  release_date_usa: "",
  release_date_tw: "",
  director: "",
  prequel_id: null,
  sequel_id: null,
  watch_order: "",
  derive_related: "",
  imdb_id: "",
  imdb_link: "",
  source_other: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultTvShow = () => ({
  tv_name_en: "",
  tv_name_cn: "",
  tv_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  season_part: "Season 1",
  region: "歐美劇",
  source_official: "",
  is_main: "",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  ep_total: "",
  ep_fin: "",
  my_rating: "",
  imdb_rating: "",
  release_date: "",
  prequel_id: null,
  sequel_id: null,
  watch_order: "",
  derive_related: "",
  imdb_id: "",
  imdb_link: "",
  source_other: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultCartoon = () => ({
  cartoon_name_en: "",
  cartoon_name_cn: "",
  cartoon_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  season_part: "",
  airing_type: "TV",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  is_main: "本傳",
  ep_total: "",
  ep_fin: "",
  my_rating: "",
  imdb_rating: "",
  length_ep_min: "",
  source_official: "",
  release_date: "",
  prequel_id: null,
  sequel_id: null,
  watch_order: "",
  derive_related: "",
  imdb_id: "",
  imdb_link: "",
  source_other: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultManga = () => ({
  manga_name_cn: "",
  manga_name_en: "",
  manga_name_roman: "",
  manga_name_jp: "",
  manga_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  region: "",
  serialization_status: "",
  reading_status: "Might Read",
  is_main: "本傳",
  vol_total: "",
  vol_fin: "",
  vol_fin_page: "",
  ch_total: "",
  ch_fin: "",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  author_plot: "",
  author_draw: "",
  release_year: "",
  end_year: "",
  anime_studio: "",
  serialization_platform: "",
  publisher_tw: "",
  derive_related: "",
  prequel_id: null,
  sequel_id: null,
  watch_order: "",
  mal_id: "",
  mal_link: "",
  anilist_link: "",
  source_other: [],
  read_next: false,
  to_reread: false,
  cover_image_file: "",
  remark: "",
});

export const defaultNovel = () => ({
  novel_name_cn: "",
  novel_name_en: "",
  novel_name_roman: "",
  novel_name_jp: "",
  novel_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  region: "",
  type: "",
  version: "",
  is_main: "本傳",
  serialization_status: "",
  reading_status: "Might Read",
  progress_display: "",
  vol_total_original: "",
  vol_total_tw: "",
  vol_fin: "",
  arc_total: "",
  arc_fin: "",
  ch_total: "",
  ch_fin: "",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  author: "",
  illustrator: "",
  release_year: "",
  end_year: "",
  publisher_tw: "",
  prequel_id: null,
  sequel_id: null,
  alternative: "",
  read_order: "",
  novel_name_each_cn: [],
  novel_name_each_en: [],
  mal_id: "",
  mal_link: "",
  anilist_link: "",
  source_other: [],
  read_next: false,
  to_reread: false,
  cover_image_file: "",
  remark: "",
});

export const defaultFranchise = () => ({
  franchise_name_en: "",
  franchise_name_cn: "",
  franchise_name_roman: "",
  franchise_name_jp: "",
  franchise_name_alt: "",
  franchise_type: "",
  my_rating: "",
  franchise_expectation: "",
  remark: "",
});

export const defaultSeries = () => ({
  franchise_id: null,
  franchise_text: "",
  series_name_en: "",
  series_name_cn: "",
  series_name_alt: "",
  remark: "",
});

// Keyed by the media-type slugs used in config/mediaRegistry.js.
export const FORM_FACTORIES = {
  anime: defaultAnime,
  "anime-movie": defaultAnimeMovie,
  movie: defaultMovie,
  "tv-show": defaultTvShow,
  cartoon: defaultCartoon,
  manga: defaultManga,
  novel: defaultNovel,
  franchise: defaultFranchise,
  series: defaultSeries,
};
