// Blank-form factories for every Add-page tab that has a form: the media
// types, the grouping tiers, and the three entity forms (studio, person,
// character).
//
// These live in config/ rather than in the add-tab components so that other
// config modules (the form-field registry) can derive field keys from them
// without importing page-level JSX. Each add-tab re-exports its own factory,
// so existing `import AnimeAddTab, { defaultAnime }` imports keep working.
//
// Values here are the BUILT-IN baseline. Admin-configured overrides from
// /api/form-defaults are layered on top by resolveDefaults() in
// hooks/useFormDefaults.js -- these factories are what the app falls back to
// when nothing is configured or the fetch fails.

export const defaultAnime = () => ({
  anime_name_en: "",
  anime_name_cn: "",
  anime_name_roman: "",
  anime_name_jp: "",
  anime_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  season_num: "",
  part_num: "",
  airing_type: "",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  is_main: "本傳",
  ep_previous: "",
  ep_total: "",
  ep_fin: "",
  ep_special: "",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  release_season: "",
  release_date: "",
  broadcast_day: "",
  broadcast_time: "",
  my_watch_day: "",
  genre_main: "",
  genre_sub: "",
  label: "",
  quality: "",
  studio: "",
  director: "",
  producer: "",
  music: "",
  distributor_tw: "",
  is_main_entry: false,
  mal_id: "",
  mal_link: "",
  exclusive_source: "",
  sources: [],
  seiyuu: "",
  watch_next: false,
  cover_image_file: "",
  remark: "",
});

export const defaultAnimeMovie = () => ({
  anime_movie_name_en: "",
  anime_movie_name_cn: "",
  anime_movie_name_roman: "",
  anime_movie_name_jp: "",
  anime_movie_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  release_date_jp: "",
  release_date_tw: "",
  length_min: "",
  studio: "",
  director: "",
  mal_id: "",
  mal_link: "",
  exclusive_source: "",
  sources: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultMovie = () => ({
  movie_name_en: "",
  movie_name_cn: "",
  movie_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  airing_status: "Finished Airing",
  watching_status: "Might Watch",
  my_rating: "",
  movie_type: "Reality",
  is_main: "本傳",
  length_min: "",
  release_date_usa: "",
  release_date_tw: "",
  director: "",
  imdb_id: "",
  imdb_link: "",
  original_source: "",
  sources: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultTvShow = () => ({
  tv_name_en: "",
  tv_name_cn: "",
  tv_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  season_part: "Season 1",
  region: "歐美劇",
  original_source: "",
  is_main: "",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  ep_total: "",
  ep_fin: "",
  my_rating: "",
  imdb_rating: "",
  release_date: "",
  imdb_id: "",
  imdb_link: "",
  sources: [],
  watch_next: false,
  to_rewatch: false,
  cover_image_file: "",
  remark: "",
});

export const defaultCartoon = () => ({
  cartoon_name_en: "",
  cartoon_name_cn: "",
  cartoon_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  season_part: "",
  airing_type: "TV",
  airing_status: "Not Yet Aired",
  watching_status: "Might Watch",
  is_main: "本傳",
  ep_total: "",
  ep_fin: "",
  my_rating: "",
  imdb_rating: "",
  length_ep_min: "",
  original_source: "",
  release_date: "",
  imdb_id: "",
  imdb_link: "",
  sources: [],
  watch_next: false,
  cover_image_file: "",
  remark: "",
});

export const defaultManga = () => ({
  manga_name_cn: "",
  manga_name_en: "",
  manga_name_roman: "",
  manga_name_jp: "",
  manga_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  region: "",
  serialization_status: "",
  reading_status: "Might Read",
  is_main: "本傳",
  vol_total: "",
  vol_fin: "",
  vol_fin_page: "",
  ch_total: "",
  ch_fin: "",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  author_plot: "",
  author_draw: "",
  release_date: "",
  end_date: "",
  anime_studio: "",
  serialization_platform: "",
  publisher_tw: "",
  mal_id: "",
  mal_link: "",
  sources: [],
  read_next: false,
  to_reread: false,
  cover_image_file: "",
  remark: "",
});

export const defaultNovel = () => ({
  novel_name_cn: "",
  novel_name_en: "",
  novel_name_roman: "",
  novel_name_jp: "",
  novel_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  region: "",
  type: "",
  version: "",
  is_main: "本傳",
  serialization_status: "",
  reading_status: "Might Read",
  progress_display: "",
  vol_total_original: "",
  vol_total_tw: "",
  vol_fin: "",
  arc_total: "",
  arc_fin: "",
  ch_total: "",
  ch_fin: "",
  my_rating: "",
  mal_rating: "",
  mal_rank: "",
  anilist_rating: "",
  author: "",
  illustrator: "",
  release_date: "",
  end_date: "",
  serialization_platform: "",
  publisher_tw: "",
  read_order: "",
  units: [],
  mal_id: "",
  mal_link: "",
  openlibrary_link: "",
  openlibrary_id: "",
  sources: [],
  read_next: false,
  to_reread: false,
  cover_image_file: "",
  remark: "",
});

export const defaultComic = () => ({
  comic_name_en: "",
  comic_name_cn: "",
  comic_name_alt: "",
  franchise_id: null,
  franchise_text: "",
  series_id: null,
  series_text: "",
  volume_label: "",
  comic_type: "",
  publisher: "",
  imprint: "",
  continuity: "",
  era: "",
  events: [],
  serialization_status: "",
  reading_status: "Might Read",
  issue_total: "",
  issue_fin: "",
  my_rating: "",
  writer: "",
  artist: "",
  release_date: "",
  end_date: "",
  publisher_tw: "",
  is_main_entry: false,
  read_order: "",
  comicvine_link: "",
  sources: [],
  read_next: false,
  to_reread: false,
  cover_image_file: "",
  remark: "",
});

export const defaultCollection = () => ({
  collection_name_en: "",
  collection_name_cn: "",
  collection_name_roman: "",
  collection_name_jp: "",
  collection_name_alt: "",
  my_rating: "",
  collection_expectation: "",
  remark: "",
});

export const defaultFranchise = () => ({
  collection_id: null,
  collection_text: "",
  franchise_name_en: "",
  franchise_name_cn: "",
  franchise_name_roman: "",
  franchise_name_jp: "",
  franchise_name_alt: "",
  franchise_type: "",
  my_rating: "",
  franchise_expectation: "",
  remark: "",
});

export const defaultSeries = () => ({
  franchise_id: null,
  franchise_text: "",
  series_name_en: "",
  series_name_cn: "",
  series_name_roman: "",
  series_name_jp: "",
  series_name_alt: "",
  my_rating: "",
  series_expectation: "Low",
  cover_entry_id: null,
  remark: "",
});

// The three Entity-group forms. An entity is credited ON entries rather than
// being an entry, so these carry none of the tracking fields above -- but they
// are still Add forms whose starting values the admin configures on /defaults.

export const defaultStudio = () => ({
  name_en: "",
  name_cn: "",
  name_jp: "",
  name_alt: "",
  display_name_field: "",
  my_rating: "",
  logo_file: "",
  country: "",
  website_url: "",
  founded_date: "",
  defunct_date: "",
  mal_id: "",
  mal_link: "",
  remark: "",
});

export const defaultPerson = () => ({
  name_en: "",
  name_cn: "",
  name_jp: "",
  name_alt: "",
  display_name_field: "",
  gender: "",
  my_rating: "",
  photo_file: "",
  remark: "",
});

// Identical in shape to a person today, but kept separate: the two are
// different tables with different futures, and a shared factory would make a
// person-only field silently appear on the character form.
export const defaultCharacter = () => ({
  name_en: "",
  name_cn: "",
  name_jp: "",
  name_alt: "",
  display_name_field: "",
  gender: "",
  my_rating: "",
  photo_file: "",
  remark: "",
});

// Keyed by the media-type slugs used in config/mediaRegistry.js, plus the
// entity tab keys from config/adminTabs.js.
export const FORM_FACTORIES = {
  anime: defaultAnime,
  "anime-movie": defaultAnimeMovie,
  movie: defaultMovie,
  "tv-show": defaultTvShow,
  cartoon: defaultCartoon,
  manga: defaultManga,
  novel: defaultNovel,
  comic: defaultComic,
  collection: defaultCollection,
  franchise: defaultFranchise,
  series: defaultSeries,
  studio: defaultStudio,
  person: defaultPerson,
  character: defaultCharacter,
};
