"""
Every media detail table must FK up to `media` on (system_id, media_type) and
pin its own type with a CHECK. Neither is autogenerated by Alembic, and a
missing one fails silently - a detail row could attach to a media row of the
wrong type, which is the thing the supertable exists to prevent.

Metadata only; no database.
"""

from sqlalchemy import CheckConstraint, ForeignKeyConstraint

from app.utils.media_resolver import MEDIA_TABLES


def test_every_media_table_has_its_composite_fk_and_check():
    missing = []
    for key, ref in MEDIA_TABLES.items():
        table = ref.model.__table__

        fks = [
            c for c in table.constraints
            if isinstance(c, ForeignKeyConstraint)
            and {col.name for col in c.columns} == {"system_id", "media_type"}
        ]
        if not fks:
            missing.append(f"{key}: no composite (system_id, media_type) FK")
        elif fks[0].name != f"fk_{table.name}_media":
            missing.append(f"{key}: FK named {fks[0].name!r}")

        checks = [
            c for c in table.constraints
            if isinstance(c, CheckConstraint)
            and c.name == f"ck_{table.name}_media_type"
        ]
        if not checks:
            missing.append(f"{key}: no ck_{table.name}_media_type")

    assert not missing, "\n".join(missing)


def test_every_media_table_declares_the_discriminator_column():
    for key, ref in MEDIA_TABLES.items():
        cols = ref.model.__table__.c
        assert "media_type" in cols, f"{key} has no media_type column"
        assert cols["media_type"].nullable is False


def test_the_composite_fk_is_deferred_on_every_type():
    """
    The parent row is written after the child (it copies public_id, minted by
    a Sequence default at INSERT time), so an immediate FK rejects every
    insert. One type left immediate would break only that type's writes.
    """
    for key, ref in MEDIA_TABLES.items():
        table = ref.model.__table__
        fk = next(
            c for c in table.constraints
            if isinstance(c, ForeignKeyConstraint)
            and {col.name for col in c.columns} == {"system_id", "media_type"}
        )
        assert fk.deferrable, f"{key}: fk_{table.name}_media is not DEFERRABLE"
        assert fk.initially == "DEFERRED", f"{key}: fk not INITIALLY DEFERRED"
