"""fix anime table and anime movie table

Revision ID: 12e2e03e7728
Revises: a07b5b312234
Create Date: 2026-04-24 16:48:34.143622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12e2e03e7728'
down_revision: Union[str, Sequence[str], None] = 'a07b5b312234'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'source_other_link')
    op.alter_column('anime_movies', 'source_other',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='source_other::jsonb')
    op.drop_column('anime_movies', 'source_other_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime_movies', sa.Column('source_other_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('anime_movies', 'source_other',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.add_column('anime', sa.Column('source_other_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
