"""remove_favorite_3x3_slot_from_franchise

Revision ID: 289f134d3bea
Revises: l0m1n2o3p4q5
Create Date: 2026-05-14 17:27:57.623517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289f134d3bea'
down_revision: Union[str, Sequence[str], None] = 'l0m1n2o3p4q5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('franchise', 'favorite_3x3_slot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchise', sa.Column('favorite_3x3_slot', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
