"""add cover_anime_id to franchise

Revision ID: 3dac0093a689
Revises: 86982d71c2f1
Create Date: 2026-04-17 09:12:12.372697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dac0093a689'
down_revision: Union[str, Sequence[str], None] = '86982d71c2f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchise', sa.Column('cover_anime_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'franchise', 'anime', ['cover_anime_id'], ['system_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'franchise', type_='foreignkey')
    op.drop_column('franchise', 'cover_anime_id')
    # ### end Alembic commands ###
