"""add alternative to novel

Revision ID: 5236445b7c91
Revises: df0d6478d558
Create Date: 2026-05-13 01:27:56.208320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5236445b7c91'
down_revision: Union[str, Sequence[str], None] = 'df0d6478d558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('novel', sa.Column('alternative', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('novel', 'alternative')
    # ### end Alembic commands ###
