"""add tv_shows table

Revision ID: 6909a0163ef5
Revises: i7j8k9l0m1n2
Create Date: 2026-04-29 11:29:12.291261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6909a0163ef5"
down_revision: Union[str, Sequence[str], None] = "i7j8k9l0m1n2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tv_shows",
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("franchise_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("tv_name_en", sa.String(), nullable=True),
        sa.Column("tv_name_cn", sa.String(), nullable=True),
        sa.Column("tv_name_alt", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("season_part", sa.String(), nullable=True),
        sa.Column("source_official", sa.String(), nullable=True),
        sa.Column("airing_status", sa.String(), nullable=True),
        sa.Column("watching_status", sa.String(), nullable=False),
        sa.Column("is_main", sa.String(), nullable=True),
        sa.Column("ep_total", sa.Integer(), nullable=True),
        sa.Column("ep_fin", sa.Integer(), nullable=True),
        sa.Column("my_rating", sa.String(), nullable=True),
        sa.Column("imdb_rating", sa.String(), nullable=True),
        sa.Column("release_date", sa.String(), nullable=True),
        sa.Column("derive_related", sa.Boolean(), nullable=True),
        sa.Column("prequel_id", sa.UUID(), nullable=True),
        sa.Column("sequel_id", sa.UUID(), nullable=True),
        sa.Column("watch_order", sa.Float(), nullable=True),
        sa.Column("imdb_id", sa.String(), nullable=True),
        sa.Column("imdb_link", sa.String(), nullable=True),
        sa.Column("source_other", sa.String(), nullable=True),
        sa.Column("source_other_link", sa.String(), nullable=True),
        sa.Column("watch_next", sa.Boolean(), nullable=True),
        sa.Column("to_rewatch", sa.Boolean(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("cover_image_file", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["franchise_id"], ["franchise.system_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["series_id"], ["series.system_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("system_id"),
    )
    op.create_index(
        op.f("ix_tv_shows_system_id"), "tv_shows", ["system_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tv_shows_system_id"), table_name="tv_shows")
    op.drop_table("tv_shows")
    # ### end Alembic commands ###
