"""add manga table

Revision ID: 7ec2ef0fced2
Revises: 4badc000f3c6
Create Date: 2026-05-05 13:48:47.216484

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7ec2ef0fced2"
down_revision: Union[str, Sequence[str], None] = "4badc000f3c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga",
        sa.Column("system_id", sa.UUID(), nullable=False),
        sa.Column("franchise_id", sa.UUID(), nullable=True),
        sa.Column("series_id", sa.UUID(), nullable=True),
        sa.Column("manga_name_en", sa.String(), nullable=True),
        sa.Column("manga_name_cn", sa.String(), nullable=True),
        sa.Column("manga_name_roman", sa.String(), nullable=True),
        sa.Column("manga_name_jp", sa.String(), nullable=True),
        sa.Column("manga_name_alt", sa.String(), nullable=True),
        sa.Column("region", sa.String(), nullable=True),
        sa.Column("is_main", sa.String(), nullable=True),
        sa.Column("serialization_status", sa.String(), nullable=True),
        sa.Column("reading_status", sa.String(), nullable=False),
        sa.Column("vol_total", sa.Integer(), nullable=True),
        sa.Column("vol_fin", sa.Integer(), nullable=False),
        sa.Column("vol_fin_page", sa.Integer(), nullable=False),
        sa.Column("ch_total", sa.Integer(), nullable=True),
        sa.Column("ch_fin", sa.Integer(), nullable=False),
        sa.Column("my_rating", sa.String(), nullable=True),
        sa.Column("mal_rating", sa.Float(), nullable=True),
        sa.Column("mal_rank", sa.String(), nullable=True),
        sa.Column("anilist_rating", sa.String(), nullable=True),
        sa.Column("author_plot", sa.String(), nullable=True),
        sa.Column("author_draw", sa.String(), nullable=True),
        sa.Column("release_year", sa.String(), nullable=True),
        sa.Column("end_year", sa.String(), nullable=True),
        sa.Column("anime_studio", sa.String(), nullable=True),
        sa.Column("serialization_platform", sa.String(), nullable=True),
        sa.Column("distributor_tw", sa.String(), nullable=True),
        sa.Column("derive_related", sa.Boolean(), nullable=True),
        sa.Column("prequel_id", sa.UUID(), nullable=True),
        sa.Column("sequel_id", sa.UUID(), nullable=True),
        sa.Column("watch_order", sa.Float(), nullable=True),
        sa.Column("mal_id", sa.Integer(), nullable=True),
        sa.Column("mal_link", sa.String(), nullable=True),
        sa.Column("anilist_link", sa.String(), nullable=True),
        sa.Column(
            "source_other", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("read_next", sa.Boolean(), nullable=True),
        sa.Column("to_reread", sa.Boolean(), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cover_image_file", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["franchise_id"], ["franchise.system_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["series_id"], ["series.system_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("system_id"),
    )
    op.create_index(op.f("ix_manga_system_id"), "manga", ["system_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_manga_system_id"), table_name="manga")
    op.drop_table("manga")
    # ### end Alembic commands ###
