"""add watch_next and to_rewatch to anime_movies

Revision ID: 8ebb04663811
Revises: j8k9l0m1n2o3
Create Date: 2026-04-30 09:33:23.990953

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "8ebb04663811"
down_revision: Union[str, Sequence[str], None] = "j8k9l0m1n2o3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("anime_movies", sa.Column("watch_next", sa.Boolean(), nullable=True))
    op.add_column("anime_movies", sa.Column("to_rewatch", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("anime_movies", "to_rewatch")
    op.drop_column("anime_movies", "watch_next")
    # ### end Alembic commands ###
