"""add notes column to tv_shows

Revision ID: c78fa567ff9a
Revises: 6909a0163ef5
Create Date: 2026-04-29 11:35:13.713510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c78fa567ff9a"
down_revision: Union[str, Sequence[str], None] = "6909a0163ef5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tv_shows",
        sa.Column("notes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tv_shows", "notes")
    # ### end Alembic commands ###
