"""add completed_at to anime

Revision ID: e53735cf60dc
Revises: 3dac0093a689
Create Date: 2026-04-17 09:27:24.132234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e53735cf60dc'
down_revision: Union[str, Sequence[str], None] = '3dac0093a689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anime', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anime', 'completed_at')
    # ### end Alembic commands ###
