"""add to_rewatch to franchise

Revision ID: ed0b5635fbf5
Revises: e20cf35a6d03
Create Date: 2026-04-17 10:17:34.836183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed0b5635fbf5'
down_revision: Union[str, Sequence[str], None] = 'e20cf35a6d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('franchise', sa.Column('to_rewatch', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('franchise', 'to_rewatch')
    # ### end Alembic commands ###
