"""add entry_planned column for seasonal table

Revision ID: fbc168649b9d
Revises: 12e2e03e7728
Create Date: 2026-04-25 23:24:17.602295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fbc168649b9d"
down_revision: Union[str, Sequence[str], None] = "12e2e03e7728"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "seasonal",
        sa.Column("entry_planned", sa.Integer(), nullable=False, server_default="0"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("seasonal", "entry_planned")
    # ### end Alembic commands ###
