"""Add the publisher_scope table.

Revision ID: pb1s2c3o4p5e
Revises: gs1p2r3o4g5

Which media types a publisher is offered on, modelled on person_role. Explicit
rather than derived from credits: a distributor added today must appear in the
anime picker before its first credit exists.

No `role` column, unlike person_role - a publisher holds exactly one role,
`publisher`, so a column carrying that constant on every row would encode
nothing. The key is (publisher_id, scope) alone, and a plain unique constraint
serves it because scope is NOT NULL, leaving no nullable column for Postgres to
treat as distinct from itself.

Schema only, and purely additive: nothing reads the table yet, and zero rows
means "offered nowhere", so no existing publisher changes behaviour.

Autogenerated, then trimmed by hand: the autogenerate pass also proposed a
media_source index/constraint swap, ix_person_name_en and a system_option index
rename, none of which belong to this change. They are pre-existing drift
between the models and the dev database and are left for whoever owns them.
"""

import sqlalchemy as sa
from alembic import op

revision = "pb1s2c3o4p5e"
down_revision = "gs1p2r3o4g5"
branch_labels = None
depends_on = None


def upgrade():
    op.create_table(
        "publisher_scope",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("publisher_id", sa.UUID(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["publisher_id"], ["publisher.system_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("publisher_id", "scope", name="uq_publisher_scope"),
    )
    op.create_index(
        op.f("ix_publisher_scope_publisher_id"),
        "publisher_scope",
        ["publisher_id"],
        unique=False,
    )


def downgrade():
    op.drop_index(
        op.f("ix_publisher_scope_publisher_id"), table_name="publisher_scope"
    )
    op.drop_table("publisher_scope")
